INSERT INTO `#h_mui` (`id`, `group`, `param`, `mui_code`, `mui_text`, `adm`) VALUES
(NULL, 'error404', 'en', 'error404-pagenotfound', 'Pages not found', '0'),
(NULL, 'error404', 'en', 'error404-describe', 'The requested page was not found on the server. Maybe the page you are looking for was deleted or moved to a new address.', '0'),
(NULL, 'error404', 'en', 'error404-go2home', 'Go to the home page', '0'),
(NULL, 'common', 'en', 'admc_add', 'add', '1'),
(NULL, 'common', 'en', 'admc_record_add', 'Record Added', '1'),
(NULL, 'Admin: buttons','en',' admc_record_edited ',' Record edited ', '1'),
(NULL, 'Admin: buttons','en',' admc_button_save ',' save ', '1'),
(NULL, 'Admin: buttons','en',' admc_button_applay ',' apply ', '1'),
(NULL, 'Admin: buttons','en',' admc_button_cancel ',' Cancel ', '1'),
(NULL, 'common', 'en', 'adm_access2part_deny', '<strong> Error: </ strong> section does not exist or access denied', '1'),
(NULL, 'common', 'en', 'adm_itemedit', 'edit', '1'),
(NULL, 'common', 'en', 'adm_itemadd', 'add', '1'),
(NULL,'', 'en', 'adm_buttonadd', 'add', '1'),
(NULL,'', 'en', 'adm_buttonsave', 'save', '1'),
(NULL,'', 'en', 'adm_buttonapplay', 'apply', '1'),
(NULL,'', 'en', 'adm_buttoncancel', 'Cancel', '1'),
(NULL, 'common', 'en', 'adm_switchno', 'no', '1'),
(NULL, 'common', 'en', 'adm_switchyes',' yes', '1'),
(NULL, 'common', 'en', 'adm_itemdelquestion', 'Delete?', '1'),
(NULL, 'Admin: Add a page', 'en', 'adm_noitems',' no records', '1'),
(NULL,'', 'en', 'adm_itemdelcanttooltip', 'can not delete', '1'),
(NULL, 'common', 'en', 'adm_itemdeltooltip', 'delete entry', '1'),
(NULL,'', 'en', 'adm_itemeditcanttooltip', 'not edit', '1'),
(NULL, 'common', 'en', 'adm_itemedittooltip', 'edit post', '1'),
(NULL, 'common', 'en', 'adm_userchecklist_showuser', 'view / edit the user in a new window', '1'),
(NULL, 'common', 'en', 'adm_userchecklist_login', 'login', '1'),
(NULL, 'common', 'en', 'adm_userchecklist_usernotset', 'user is not specified', '1'),
(NULL, 'common', 'en', 'adm_userchecklist_setuser', 'set user', '1'),
(NULL,'', 'en', 'adm_mailfromsite_usernotset', 'user is not specified', '1'),
(NULL,'', 'en', 'adm_mailfromsite_nomails',' no mail ', '1'),
(NULL,'', 'en', 'adm_mailfromsite_from', 'From', '1'),
(NULL,'', 'en', 'adm_mailfromsite_to', 'To', '1'),
(NULL,'', 'en', 'adm_mailfromsite_thema', 'Subject', '1'),
(NULL,'', 'en', 'adm_mailfromsite_date', 'date', '1'),
(NULL,'', 'en', 'adm_mailfromsite_senderror', 'Failed to send', '1'),
(NULL,'', 'en', 'adm_showsaveico_save', 'save', '1'),
(NULL,'', 'en', 'adm_savex_savemes',' amended ', '1'),
(NULL,'', 'en', 'adm_switchrow_savemes',' recording edited ', '1'),
(NULL, 'common', 'en', 'adm_delrow_del', 'record deleted', '1'),
(NULL,'', 'en', 'adm_closeeditform_unfilled', 'not completed a required field', '1'),
(NULL,'', 'en', 'fs_directory_nochoosedir', 'folder is not selected', '1'),
(NULL,'', 'en', 'fs_directory_choosefolder', 'select the folder / upload files (photos)', '1'),
(NULL,'', 'en', 'fs_directory_setthisdir', 'select folder', '1'),
(NULL, 'common', 'en', 'adm_showfile_delimg', 'Delete image', '1'),
(NULL,'', 'en', 'adm_showfile_delfile', 'delete file', '1'),
(NULL, 'common', 'en', 'adm_showfile_notuploaded', 'file not loaded', '1'),
(NULL, 'common', 'en', 'adm_showfile_choosefile', 'Select a file, max. Size', '1'),
(NULL,'', 'en', 'adm_showfile_upnotallowed', 'Downloading files is prohibited in the settings of PHP (php.ini). Contact your server administrator.', '1'),
(NULL, 'common', 'en', 'adm_showfile_upnodir', 'The directory to load the file does not exist', '1'),
(NULL, 'common', 'en', 'adm_lidedit', 'edit', '1'),
(NULL, 'Admin: Add a page', 'en', 'adm_autotranslit', 'automatic transliteration url', '1'), 
(NULL, 'common', 'en', 'adm_lidwar', 'Warning: the page address has changed. This can lead to broken links on this site.', '1'),
(NULL, 'common', 'en', 'adm_lidwarretdef', 'return to the original address', '1'),
(NULL,'', 'en', 'adm_addprelid', 'Add vnachalo references address the parent page', '1'),
(NULL, 'common', 'en', 'adm_uploadfile_ok', 'file is loaded', '1'),
(NULL,'', 'en', 'adm_uploadfile_err', 'error while loading file', '1'),
(NULL,'', 'en', 'adm_uploadfile_unsupfiletype', 'Invalid file type', '1'),
(NULL,'', 'en', 'adm_uploadfile_filesaveerror', 'error when saving a file', '1'),
(NULL,'', 'en', 'adm_uploadfile_savedascopy', 'file with the specified name exists, a new file is uploaded under the username', '1'),
(NULL,'', 'en', 'adm_uploadfile_savesuc', 'file download was successful', '1'),
(NULL,'', 'en', 'adm_deletefile_notfound', 'file not found', '1'),
(NULL,'', 'en', 'adm_changepas_war1', 'Password not changed. You must enter a new password and confirm it.', '1'),
(NULL,'', 'en', 'adm_changepas_war2', 'Password not changed. The new password and confirm password do not match.', '1'),
(NULL,'', 'en', 'adm_changepas_war3', 'Password not changed. Invalid current password.', '1'),
(NULL,'', 'en', 'adm_changepas_ok1', 'Password changed.', '1'),
(NULL,'', 'en', 'adm_changepas_war4', 'Password not set. You must enter a password and confirm it.', '1'),
(NULL,'', 'en', 'adm_changepas_war5', 'The password is not specified. The password and confirmation password do not match.', '1'),
(NULL,'', 'en', 'adm_changepas_ok2', 'password set.', '1'),
(NULL, 'common', 'en', 'admc_filter-strok', 'Lines per page', '1'),
(NULL,'', 'en', 'record_added', 'Record Added a', '1'),
(NULL,'', 'en', 'record_edited', 'record otredaktrovana', '1'),
(NULL,'', 'en', 'record_unsaved', 'The information is not saved', '1'),
(NULL, 'common', 'en', 'password_cur', 'Current password', '1'),
(NULL, 'common', 'en', 'password_new1', 'New parol1', '1'),
(NULL, 'common', 'en', 'password_new2', 'New parol2', '1'),
(NULL, 'common', 'en', 'email', 'Contact email', '1'), 
(NULL, 'common', 'en', 'button_save', 'save', '1'),
(NULL,'', 'en', 'admc_title', 'content', '1'),
(NULL, 'common', 'en', 'sort_by_parent_page', 'Sort Records to record', '1'),
(NULL, 'common', 'en', 'go_up', 'Jump higher', '1'),
(NULL, 'Admin: buttons','en',' save ',' Save the sort ', '1'),
(NULL, 'Admin: buttons','en',' cancel ',' Cancel (to return, do not save),', '1'),
(NULL, 'common', 'en', 'no_published', 'Writing is not published on the website', '1'),
(NULL, 'common', 'en', 'sort_sub_pages',' Sort subentries', '1'),
(NULL,'', 'en', 'select-manage: admc_title', 'Office Select', '1'),
(NULL, 'common', 'en', 'admc_error_duplicateurl', 'Error. Page with this url already exists (Step 2)', '1'),
(NULL, 'common', 'en', 'admc_error_nourl', 'Error. No target url of the page (Step 2)', '1'),
(NULL,'', 'en', 'admc_error_notitle', 'Error. Zogolovok Not specified page (Step 2)', '1'),
(NULL,'', 'en', 'admc_error_noparent', 'Error. Not selected partition to add (Step 1)', '1'),
(NULL, 'common', 'en', 'admc_record_edit', 'Record edited', '1'),
(NULL, 'Admin: buttons','en',' admc1_button_save ',' save ', '1'),
(NULL, 'Admin: buttons','en',' admc1_button_applay ',' apply ', '1'),
(NULL, 'Admin: buttons','en',' admc1_button_cancel ',' Cancel ', '1'),
(NULL, 'Admin: Add a page', 'en', 'step', 'Step', '1'),
(NULL,'', 'en', 'from', 'out', '1'),
(NULL,'', 'en', 'click_next', 'Upon completion of the selection, press "Next"', '1'),
(NULL,'', 'en', 'click_save', 'Upon completion of the selection, click "save" ', '1'),
(NULL, 'Admin: Add a page', 'en', 'add_root', '- Root -', '1'),
(NULL, 'Admin: Add a page', 'en', 'form-title', 'Title', '1'),
(NULL, 'Admin: Add a page', 'en', 'form-url', 'page address', '1'),
(NULL, 'Admin: Add a page', 'en', 'title_pathway', '<b> Breadcrumbs </ b> (<a href = "http://ru.wikipedia.org/wiki/% D0% 9D % D0% B0% D0% B2% D0% B8% D0% B3% D0% B0% D1% 86% D0% B8% D0% BE% D0% BD% D0% BD% D0% B0% D1% 8F_% D1 % 86% D0% B5% D0% BF% D0% BE% D1% 87% D0% BA% D0% B0 "target =" _blank "> know what the bread crumbs </ a>),', '1'),
(NULL, 'Admin: Add a page', 'en', 'form-include_in_pathway', 'Use in HK', '1'),
(NULL, 'Admin: Add a page', 'en', 'form-pathway', 'Type in HK', '1'),
(NULL,'', 'en', 'tooltip-pathway', 'specified text in this field, you change the header of this page for output to a site in the bread crumbs', '1'),
(NULL, 'Admin: Add a page', 'en', 'selectmenu', 'Select', '1'),
(NULL, 'Adm: menu', 'en', 'selectparentpunkt', 'Parent item', '1'),
(NULL, 'Adm: menu', 'en', 'textoflink', 'Link text', '1'),
(NULL, 'Adm: menu', 'en', 'linksort', 'Sort', '1'),
(NULL, 'Adm: menu', 'en', 'openlinkin', 'open', '1'),
(NULL, 'Adm: menu', 'en', 'openlinkin_self', 'in the same window', '1'),
(NULL, 'Adm: menu', 'en', 'openlinkin_blank', 'new window', '1'),
(NULL,'', 'en', 'admc_button_back', 'back', '1'),
(NULL,'', 'en', 'admc_button_next', 'continue', '1'),
(NULL, 'Admin: Add a page', 'en', 'add_here', 'will be posted here', '1'),
(NULL, 'Admin: Add a page', 'en', 'textoflinkgettitle', 'Put the page title', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: admc_title', 'Manage languages', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: chooselan', 'Choose Language', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: nogroup', '- no band -', '1'),
(NULL,'', 'en', 'mui_control: selectpart', 'Part of the site', '1'),
(NULL,'', 'en', 'mui_control: isadm0', 'the site', '1'),
(NULL,'', 'en', 'mui_control: isadm1', 'Admin', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: selectgroup', 'Select group', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: allgroups',' - all of - ', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: group_self', 'New group', '1'),
(NULL, 'AdminkaBog: Controlling Language', 'en', 'mui_control: group', 'Grappa', '1'),
(NULL, 'Adm: menu', 'en', 'menulist: admc_title', 'Menu', '1'),
(NULL, 'Adm: menu', 'en', 'menulist_items: admc_title', 'menu / menu items', '1'),
(NULL,'', 'en', 'savebutton', 'Save Changes', '1'),
(NULL,'', 'en', 'go_sort_title', 'Sort photos', '1'),
(NULL,'', 'en', 'proceedsort', 'Before sorting, save the data entered, otherwise they will be lost. Continue?', '1'),
(NULL,'', 'en', 'go_sort_diti', 'Sort the list of categories', '1'),
(NULL,'', 'en', 'nopictures',' no matches pictures', '1'),
(NULL,'', 'en', 'tpl_site', 'Site', '1'),
(NULL, 'Admin: Dialogs','en',' sitemap_sort_dialog_title ',' Sort pages', '1'),
(NULL, 'Admin: map', 'en', 'sitemap_sort_btn_title', 'Sort pages', '1'),
(NULL, 'Admin: map', 'en', 'tpl_sitemaploading', 'site map loading, please wait ...', '1'),
(NULL, 'common', 'en', 'userconf', 'User Settings', '1'),
(NULL, 'Admin: map', 'en', 'userconflink', 'Change Password', '1'),
(NULL, 'Admin: map', 'en', 'exitfromadm', 'Exit from the panel of administration', '1'),
(NULL, 'Admin: FileManager', 'en', 'filemanager_title', 'you are here', '1'),
(NULL,'', 'en', 'thisisnotdir', 'The requested directory does not exist', '1'),
(NULL,'', 'en', 'uploadedfilescol', 'Uploaded files', '1'),
(NULL,'', 'en', 'createdir_err', 'folder is not created', '1'),
(NULL, 'Admin: FileManager', 'en', 'createdir_ok', 'Folder created', '1'),
(NULL, 'Admin: FileManager', 'en', 'loadwait', 'Please wait, loading folder contents', '1'),
(NULL,'', 'en', 'cantuploadfile', 'No permission to create folders and upload files to this folder.', '1'),
(NULL, 'Admin: FileManager', 'en', 'uplfilesbtn', 'upload files', '1'),
(NULL,'', 'en', 'uploadfile', 'Upload File (s),to this folder', '1'),
(NULL,'', 'en', 'upmorefiles',' add fields to upload files', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_click_text', 'Click to select the files', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_uploading_text', 'Loading', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_complete_text', 'Download complete', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_pending_text', 'Waiting for boot', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_max_text', 'file limit reached', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_valid_text', 'Invalid file type', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_size_failure_text', 'File size exceeded', '1'),
(NULL, 'Admin: FileManager', 'en', 'flaupl_progress_text', 'Loading', '1'),
(NULL, 'Admin: FileManager', 'en', 'max_file_size', 'The maximum size of one file', '1'),
(NULL, 'Admin: FileManager', 'en', 'createfolder', 'Create folder here', '1'),
(NULL, 'Admin: FileManager', 'en', 'createfoldername', 'Name the folder', '1'),
(NULL, 'Admin: FileManager', 'en', 'createfolderdescr', 'Description Folder', '1'),
(NULL, 'Admin: FileManager', 'en', 'delselected', 'Delete selected files / folders', '1'),
(NULL, 'Admin: FileManager', 'en', 'needdirname', 'Specify the name of sozdovaemoy folder', '1'),
(NULL, 'Admin: FileManager', 'en', 'deletequestion', 'All files and folders will be removed permanently. Delete?', '1'),
(NULL, 'Admin: FileManager', 'en', 'contextmenu_delete', 'Delete', '1'),
(NULL, 'Admin: FileManager', 'en', 'contextmenu_properties',' Properties', '1'),
(NULL,'', 'en', 'admc_bm-editor', 'Text Editor', '1'),
(NULL, 'List of components','en',' component-manage: admc_title ',' List of components', '1'),
(NULL, 'List of components','en',' admc_newtable_created ',' A new table component made ', '1'),
(NULL,'', 'en', 'admc_newtable_notcreated_ex', 'A new table component is not created. The table with the same name already exists', '1'),
(NULL,'', 'en', 'admc_oldtable_del', 'The old table component is removed', '1'),
(NULL,'', 'en', 'admc_newtable_renamed', 'The old table is renamed to the new component name', '1'),
(NULL,'', 'en', 'admc_newtable_norenamed_ex', 'The old table component is not renamed the new name. A table with that name already exists', '1'),
(NULL,'', 'en', 'admc_js_error1', 'Error: Failed to find a cell with config', '1'),
(NULL, 'List of components','en',' admc_js_txt1 ',' The specified settings', '1'),
(NULL, 'List of components','en',' admc_conf_createtable_type1 ',' Only if there is such a name ', '1'),
(NULL, 'List of components','en',' admc_conf_createtable_type2 ',' Replace existing with this name ', '1'),
(NULL, 'List of components','en',' admc_conf_createtable_type3 ',' Rename the old to the new name ', '1'),
(NULL, 'List of components', 'en', 'admc_conf_createtable', 'C table component (parameter: <i> tbl </ i >):', '1'), 
(NULL, 'List of components','en',' admc_conf_createtable-0 ',' do nothing ', '1'),
(NULL, 'List of components','en',' admc_conf_createtable-1 ',' Create the condition of creation: ', '1'),
(NULL, 'List of components','en',' admc_conf_createtable-2 ',' Delete ', '1'),
(NULL,'', 'en', 'admc_create_config_tbl-2-confirm', 'Delete the current table component? The data will be lost.', '1'),
(NULL,'', 'en', 'admc_conf_createtable_type2_confirm', 'Remove the existing table with the same name (if any)? All data will be permanently deleted.', '1'),
(NULL,'', 'en', 'admc_conf_createtable_type12_confirm1', 'Existing table component will be removed. Continue?', '1'),
(NULL, 'Admin: general settings','en',' adm_pagetitle ',' Site Manager ', '1'),
(NULL,'', 'en', 'adm_exitq', 'Exit from the Control Panel?', '1'),
(NULL,'', 'en', 'adm_exit', 'exit', '1'),
(NULL, 'pagination', 'en', 'adm_page', 'Page', '1'),
(NULL, 'pagination', 'en', 'adm_pagefrom', 'out', '1'),
(NULL,'', 'en', 'adm_tomainpage', 'home', '1'),
(NULL,'', 'en', 'adm_previouspage', 'previous', '1'),
(NULL, 'pagination', 'en', 'adm_topage', 'move on', '1'),
(NULL, 'pagination', 'en', 'adm_page1', 'page', '1'),
(NULL, 'pagination', 'en', 'adm_nextpage', 'next', '1'),
(NULL,'', 'en', 'adm_tolastpage', 'at last', '1'),
(NULL, 'Admin: about CMS', 'en', 'cms_core_version', 'kernel version', '1'),
(NULL, 'Admin: about CMS', 'en', 'cms_adm_version', 'version admin', '1'),
(NULL, 'Admin: Dialogs', 'en', 'dialogloadstat', 'Loading ...', '1'),
(NULL, 'login page', 'en', 'adm_avtorization', 'Authorization', '1'),
(NULL, 'login page', 'en', 'adm_login', 'login', '1'),
(NULL, 'login page', 'en', 'adm_enter', 'Log', '1'),
(NULL, 'login page', 'en', 'adm_password', 'password', '1'),
(NULL, 'login page', 'en', 'adm_cms',' management system to your website ', '1'),
(NULL,'', 'en', 'adm_ajwaitdursaving', 'Please wait, adding ...', '1'),
(NULL, 'common', 'en', 'adm_ajsaved', 'Saved', '1'),
(NULL,'', 'en', 'rxstat_no', 'no', '1'),
(NULL,'', 'en', 'rxstat_createmuifile', 'Create the file', '1'),
(NULL,'', 'en', 'rxstat_params_list_def', 'Default', '1'),
(NULL, 'Admin: map', 'en', 'tpl_openpageinnw', 'open the page in a new window', '1'),
(NULL, 'common', 'en', 'content_inside', 'Inside the content:', '1'),
(NULL, 'Admin: map', 'en', 'tpl_pagetype', 'type', '1'),
(NULL, 'Admin: map', 'en', 'tpl_editpage', 'edit page', '1'),
(NULL, 'Admin: map', 'en', 'editbutton', 'edit', '1'),
(NULL, 'Admin: map', 'en', 'tpl_delpage', 'delete page', '1'),
(NULL,'', 'en', 'tpl_movepagedown', 'to move the page below', '1'),
(NULL,'', 'en', 'tpl_movepageup', 'move page above', '1'),
(NULL, 'common', 'en', 'root', 'root', '1'),
(NULL, 'common', 'en', 'ls_sel_self', 'his version', '1'),
(NULL, 'common', 'en', 'ls_sel_fromlist', 'the list', '1'),
(NULL, 'List of components','en',' admc_paramedited ',' Settings edited ', '1'),
(NULL,'', 'en', 'admc_parameditederr', 'error when editing the settings', '1'),
(NULL, 'List of components','en',' admc_fieldadded ',' Field added ', '1'),
(NULL,'', 'en', 'admc_fieldaddederr', 'error when adding a field', '1'),
(NULL, 'common', 'en', 'admc_fielddel', 'field deleted', '1'),
(NULL,'', 'en', 'admc_fielddelerr', 'Error deleting field', '1'),
(NULL, 'List of components','en',' admc_tbhat_field ',' DB field ', '1'),
(NULL, 'List of components','en',' admc_tbhat_mui ',' mui code ', '1'),
(NULL, 'List of components','en',' admc_tbhat_type ',' type fields', '1'),
(NULL, 'List of components','en',' admc_tbhat_params', 'Options', '1'),
(NULL, 'List of components','en',' admc_tbhat_edit ',' Edit ', '1'),
(NULL, 'List of components','en',' admc_tbhat_del ',' Delete ', '1'),
(NULL, 'List of components','en',' admc_tbhat_nosort ',' Sort ', '1'),
(NULL, 'List of components','en',' admc_tbhat_sort ',' order ', '1'),
(NULL, 'List of components','en',' admc_tbhat_public ',' Show ', '1'),
(NULL, 'List of components','en',' admc_tbhat_act ',' action ', '1'),
(NULL, 'common', 'en', 'admc_tdmanage_delconf', 'Remove field?', '1'),
(NULL, 'List of components','en',' admc_addfield ',' Add field ', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_lb_type_dir', 'type', '1'),
(NULL,'', 'en', 'prop_val_type_dir', 'File Folder', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_lb_type_file', 'File', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_lb_type_name', 'Name', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_val_type_file_user', 'File Manager', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_val_type_file_ondisk', 'on the drive (to create links to the file)', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_val_type_file_link', 'Link to file to insert into the editor', '1'),
(NULL, 'Admin: FileManager', 'en', 'prop_lb_size', 'size', '1'),
(NULL,'', 'en', 'prop_lb_', 'no_mui: prop_lb_', '1'), 
(NULL, 'Admin: FileManager', 'en', 'prop_save', 'Save and close the window', '1'),
(NULL,'', 'en', 'file_namedisk_exists',' The file or folder with that name already exists on disk ', '1'),
(NULL,'', 'en', 'file_namefmdir_exists',' A folder with that name in the file manager already exists', '1'),
(NULL,'', 'en', 'file_namefm_exists',' file with this name in the file manager already exists', '1'),
(NULL,'', 'en', 'error', 'Error', '1'),
(NULL, 'Admin: FileManager', 'en', 'goback', 'back', '1'),
(NULL, 'Admin: FileManager', 'en', 'emptydir', 'folder is empty', '1'),
(NULL, 'List of components','en',' admc_js_txt2 ',' Share settings', '1'),
(NULL,'', 'en', 'admc_edbmadd', 'A new tab is added', '1'),
(NULL,'', 'en', 'admc_edbmadderr', 'Error adding new bookmarks', '1'),
(NULL, 'List of components','en',' self_var ',' his version ', '1'),
(NULL, 'common', 'en', 'act_del', 'Delete', '1'),
(NULL, 'List of components','en',' bmsorttitle ',' order ', '1'),
(NULL, 'List of components','en',' addfieldtitle ',' + add a field ', '1'),
(NULL, 'List of components','en',' admc_tbhat_typedb ',' type of DB field ', '1'),
(NULL, 'List of components','en',' admc_tbhat_tooltipmui ',' mui tips', '1'),
(NULL, 'List of components','en',' admc_tbhat_req ',' Required ', '1'),
(NULL, 'List of components','en',' admc_tbhat_useinsql ',' in the sql ', '1'), 
(NULL, 'common', 'en', 'act_move1', 'Move To', '1'),
(NULL, 'common', 'en', 'act_move', 'Move to another tab', '1'),
(NULL, 'List of components','en',' addbmtitle ','Add bookmark or', '1'),
(NULL,'', 'en', 'admc_fieldadderror', 'error when adding a field', '1'),
(NULL,'', 'en', 'admc_fieldediterror', 'error when editing field', '1'),
(NULL,'', 'en', 'admc_fieldedited', 'Field edited', '1'),
(NULL, 'List of components','en',' admc_tdmanage_table ',' database table ', '1'),
(NULL, 'List of components','en',' admc_tdmanage_field ',' field ', '1'),
(NULL, 'List of components','en',' admc_tdmanage_type ',' type (length / value),', '1'),
(NULL, 'List of components','en',' admc_tdmanage_default ',' default ', '1'),
(NULL, 'List of components','en',' admc_tdmanage_edit ',' Edit ', '1'),
(NULL, 'List of components','en',' admc_tdmanage_del ',' Delete ', '1'),
(NULL, 'List of components','en',' admc_tdmanage_addtitle ',' Add field ', '1'),
(NULL, 'List of components','en',' admc_addafter ',' add post ', '1'),
(NULL, 'common', 'en', 'adm_ajlogin', 'login', '1'),
(NULL, 'common', 'en', 'adm_ajfio', 'Fillot', '1'),
(NULL, 'common', 'en', 'adm_ajset', 'Select', '1'),
(NULL, 'common', 'en', 'adm_ajsetusernotify', 'User selected', '1'),
(NULL, 'common', 'en', 'adm_ajcloseuserlist', 'Cancel', '1'),
(NULL, 'buttons add pages','en',' tpl_addpart ',' Add ', '1'),
(NULL, 'buttons add pages','en',' add_button_21 ',' Section ', '1'),
(NULL, 'buttons add pages','en',' add_button_2 ',' Text Page ', '1'),
(NULL, 'List of components','en',' admc_confparams_tooltip_tbl ',' Table of content components', '1'),
(NULL, 'List of components','en',' admc_confparams_tooltip_trashfname ',' field name the database table to which store to basket ', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_userfname', 'database field name with id of a user', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_skin', 'skin', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_wys_type', 'editor type', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_class', 'CSS class name', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_default_checked', 'checked by default', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_sub_page_tbl', 'Таблица компонента, на котором работают подстраницы к данной странице', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_sub_page_of', 'Сортировать список подстраниц по этому полю БД из таблицы компонента подстраниц', '1'),
(NULL, 'God : params of a component', 'en', 'admc_confparams_tooltip_sub_page_oc', 'Условие сортировки подстраниц при наборе', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'admc_bm-metadatas', 'Метаданные', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-f-title', 'title', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-f-keywords', 'keywords', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-f-description', 'description', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-f-title_autofill', 'дополнение title', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-t-title', 'используется, если не задан конкретный title страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-t-keywords', 'используется, если не задан конкретный keywords страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-t-description', 'используется, если не задан конкретный description страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'en', 'config-t-title_autofill', 'подставляется к title каждой страницы справа', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'ph_set_noimg', 'No images', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'ph_set_delimg', 'Delete image', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'ph_set_delimgconfirm', 'The image will be deleted. Continnue?', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'photogalery_addph_tooltip', 'Click "Click to select the files" below and choose files for uploading. After the uploading, click "Done"', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'photogalery_addph_fileexts', 'Allowed file types', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'photogalery_addph_done', 'Done', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'photogalery_addph_button', 'Upload images', '1'),
(NULL, 'admin : photogalery_add_photo', 'en', 'photogalery_addph_noiderror', 'Save the page to be able to upload photos. Click "Save"or "Apply"', '1');