CREATE TABLE IF NOT EXISTS `#h_adm_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `text` varchar(35) NOT NULL DEFAULT '',
  `link` varchar(255) NOT NULL DEFAULT '',
  `img` varchar(255) NOT NULL DEFAULT '',
  `target` varchar(15) NOT NULL DEFAULT '',
  `status` varchar(255) NOT NULL DEFAULT '',
  `mid` int(11) NOT NULL DEFAULT '0',
  `sort` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='меню админки';
CREATE TABLE IF NOT EXISTS `#h_components` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` smallint(6) NOT NULL DEFAULT '0',
  `title` varchar(200) NOT NULL DEFAULT '',
  `adm_title` varchar(200) NOT NULL DEFAULT '',
  `man_title` varchar(200) NOT NULL DEFAULT '',
  `url` varchar(200) DEFAULT NULL,
  `system` enum('0','1') DEFAULT '0',
  `sort` smallint(6) NOT NULL DEFAULT '0',
  `version` varchar(50) NOT NULL DEFAULT '',
  `cache_page` enum('0','1') NOT NULL DEFAULT '0',
  `cache_page_ttl` smallint(6) NOT NULL DEFAULT '0',
  `config` text NOT NULL,
  `add_button` enum('','razdel','content') NOT NULL DEFAULT '',
  `tpl_file` varchar(255) DEFAULT NULL,
  `get_subpages` smallint(6) NOT NULL DEFAULT '0',
  `parent_parts` varchar(255) NOT NULL DEFAULT '',
  `use_component` varchar(100) NOT NULL DEFAULT '',
  `limit` smallint(6) NOT NULL DEFAULT '0',
  `enabled` enum('0','1') NOT NULL DEFAULT '0',
  `content_tpl_by` int(11) NOT NULL DEFAULT '0',
  `nodelete` enum('0','1') NOT NULL default '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='components of this site' AUTO_INCREMENT=28 ;
INSERT INTO `#h_components` (`id`, `pid`, `title`, `adm_title`, `man_title`, `url`, `system`, `sort`, `version`, `cache_page`, `cache_page_ttl`, `config`, `add_button`, `tpl_file`, `get_subpages`, `parent_parts`, `use_component`, `limit`, `enabled`, `content_tpl_by`) VALUES
(2, 0, 'text', 'text', 'Текстовая страница', '', '0', 0, '1.0.', '0', 0, 'tbl=__textcontent\r\neditbut-apply=1', 'content', 'text.php', 0, '0', 'default', 0, '1', 0),
(12, 0, '', 'pageconfig', 'Настройка страницы', '', '0', 0, '', '0', 0, 'tbl=__sitemap\r\neditbut-apply=1', '', '', 0, '', '', 0, '0', 0),
(3, 0, '', 'config', 'Настройка сайта', '', '0', 0, '1.0.', '0', 0, 'tbl=__config\r\neditbut-save=0\r\neditbut-apply=1\r\neditbut-cancel=0\r\ndefid=1', '', '', 0, '', '', 0, '0', 0),
(4, 0, '', 'component-manage', 'Управление компонентами', '', '0', 0, '1.0.', '0', 0, 'tbl=h_components\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1\r\npidfield=pid', '', '', 0, '', '', 0, '0', 0),
(5, 0, '', 'select-manage', 'Управление selectами', '', '0', 0, '', '0', 0, 'tbl=h_components_selects\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1', '', '', 0, '', '', 0, '0', 0),
(14, 0, '', 'menulist', 'Список меню', '', '0', 0, '', '0', 0, 'tbl=__menulist\r\neditbut-apply=1\r\neditbut-save=1\r\neditbut-cancel=1\r\nsort_fieldtitle=name\r\nsort_blocksstyle=\r\nsort_sqlextra=', '', '', 0, '', '', 0, '0', 0),
(15, 14, '', 'menulist/items', 'Пункты меню', '', '0', 0, '', '0', 0, 'tbl=__menupunkti\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1\r\npidfield=pid\r\nsort_fieldtitle=name\r\nsort_blocksstyle=\r\nsort_sqlextra=&& `mid`={mid}', '', '', 0, '', '', 0, '0', 0),
(18, 20, 'foto', 'foto', 'Фотография', '', '0', 0, '', '0', 0, 'tbl=__foto\r\ntrashfname=name\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\neditbut-apply=1', 'content', '', 0, '20', 'default', 0, '0', 0),
(19, 0, '', '', 'Фотогалерея', '', '0', 0, '', '0', 0, '', 'razdel', 'fotogalery_onecat.php', 1, 'root', 'default', 1, '0', 0),
(20, 19, '', 'fotogalery', 'Категория фотогалереи', NULL, '0', 0, '', '0', 0, 'tbl=__foto\r\ntrashfname=name\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1\r\nsc_colonpage=0\r\nsc_colonsubpage=1', 'razdel', 'fotogalery_onecat.php', 0, '19', 'default', 0, '0', 0),
(21, 0, '', '', 'Раздел', '', '0', 0, '', '0', 0, '', 'razdel', '', 0, '0', 'default', 0, '1', 0),
(22, 0, '', '', 'Каталог', '', '0', 0, '', '0', 0, 'sc_colonsubpage=3\r\nsc_colonpage=10', 'razdel', 'cat_onecat.php', 1, 'root', 'catalog_item', 1, '0', 0),
(23, 22, '', 'catalog', 'Категория каталога', 'catalog_item_edit', '0', 1, '', '0', 0, 'tbl=__catalog_cat\r\ntrashfname=name\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1\r\nsc_col_subpages_0=2\r\nsc_colonpage=21', 'razdel', 'cat_onecat.php', 1, '22,23', 'catalog_item', 0, '0', 25),
(25, 23, '', 'catalog_item', 'Единица продукции', '', '0', 0, '', '0', 0, 'tbl=__catalog\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1', 'content', '', 0, '23', 'default', 0, '0', 0),
(27, 0, '', 'orders_history', 'История покупок', '', '0', 0, '', '0', 0, 'tbl=__orders\r\n\r\neditbut-save=1\r\neditbut-apply=1\r\neditbut-cancel=1\r\ncolonpage_var=10,20,50\r\ncolonpage_def=20\r\nsc_colonpage=10', 'razdel', 'orders_history.php', 0, 'root', 'orders_history', 1, '0', 0);
CREATE TABLE IF NOT EXISTS `#h_components_listedittable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `com_id` int(11) NOT NULL DEFAULT '0',
  `db_fname` varchar(255) NOT NULL DEFAULT '',
  `db_fieldtype` enum('txt','txtint','int','nl2br','flt') NOT NULL DEFAULT 'txt',
  `mui_title` varchar(50) DEFAULT NULL,
  `type` enum('txt','lid','checkbox','password','select','js-select','link-select','txtarea','wys','date','file','hid','chuser','mailfromsite','fs_directory','foto_list') DEFAULT 'txt',
  `req` enum('0','1') NOT NULL DEFAULT '0',
  `tooltip` varchar(255) NOT NULL DEFAULT '',
  `sort` smallint(6) NOT NULL DEFAULT '0',
  `public` enum('0','1') NOT NULL DEFAULT '1',
  `params` text NOT NULL,
  `useinquery` enum('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=209 ;
INSERT INTO `#h_components_listedittable` (`id`, `pid`, `com_id`, `db_fname`, `db_fieldtype`, `mui_title`, `type`, `req`, `tooltip`, `sort`, `public`, `params`, `useinquery`) VALUES
(1, 0, 2, '', 'txt', 'admc_bm-content', 'txt', '0', '', 0, '1', '', '1'),
(5, 1, 2, 'text', 'txt', 'admc_comedit-text', 'wys', '0', '', 0, '1', 'w=100%\r\nh=400', '1'),
(21, 0, 3, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(22, 21, 3, 'home_url', 'txt', 'admc_comedit-home_url', 'txt', '1', '', 2, '1', 'style=width:100%', '1'),
(23, 21, 3, 'tpl', 'txt', 'admc_comedit-tpl', 'txt', '1', '', 4, '0', 'style=width:100%', '1'),
(24, 21, 3, 'adm_tpl', 'txt', 'admc_comedit-adm_tpl', 'txt', '1', '', 5, '0', 'style=width:100%', '1'),
(25, 21, 3, 'close', 'txtint', 'admc_comedit-close', 'checkbox', '0', '', 3, '0', '', '1'),
(26, 21, 3, 'gostat', 'txtint', 'admc_comedit-gostat', 'checkbox', '0', '', 0, '0', '', '1'),
(27, 21, 3, 'use_trash', 'txtint', 'admc_comedit-use_trash', 'checkbox', '0', '', 0, '0', '', '1'),
(28, 21, 3, 'use_param', 'txtint', 'admc_comedit-use_param', 'checkbox', '0', '', 0, '0', '', '1'),
(29, 21, 3, 'debug', 'txtint', 'admc_comedit-debug', 'checkbox', '0', '', 0, '0', '', '1'),
(104, 21, 3, 'cemail', 'txt', 'form-cemail', 'txt', '1', '', 6, '1', '', '1'),
(34, 21, 3, 'ipstoplist', 'txt', 'admc_comedit-ipstoplist', 'txtarea', '0', 'admc_comedit-ipstoplist-tooltip', 0, '0', 'w=100%\r\nh=100', '1'),
(35, 21, 3, 'admin_par', 'txt', 'admc_comedit-admin_par', 'select', '0', '', 0, '0', 'selectid=1', '1'),
(36, 21, 3, 'charset', 'txt', 'admc_comedit-charset', 'txt', '0', '', 0, '0', '', '1'),
(40, 39, 4, 'man_title', 'txt', 'admclist_man_title', 'txt', '0', '', 0, '1', 'style=width:100%;', '1'),
(39, 0, 4, '', 'txt', 'admc_bm-content', 'txt', '0', '', 0, '1', '', '1'),
(41, 39, 4, 'adm_title', 'txt', 'admclist_adm_title', 'txt', '0', '', 0, '1', 'style=width:100%;', '1'),
(42, 39, 4, 'title', 'txt', 'admclist_title', 'txt', '0', '', 0, '0', 'style=width:100%;', '1'),
(43, 39, 4, 'url', 'txt', 'admclist_url', 'txt', '0', '', 0, '0', 'style=width:100%;', '1'),
(44, 39, 4, 'sort', 'int', 'admclist_sort', 'txt', '0', '', 0, '0', '', '1'),
(45, 39, 4, 'cache_page', 'txtint', 'admclist_cache_page', 'checkbox', '0', '', 0, '1', '', '1'),
(46, 39, 4, 'cache_page_ttl', 'int', 'admclist_cache_page_ttl', 'txt', '0', '', 0, '1', '', '1'),
(47, 39, 4, 'version', 'txt', 'admclist_version', 'txt', '0', '', 0, '0', '', '1'),
(48, 39, 4, 'config', 'txt', 'admclist_config', 'txtarea', '0', '', 0, '1', 'h=130\r\nw=100%', '1'),
(49, 39, 4, 'pid', 'int', 'admclist_pid', 'select', '0', '', 0, '1', 'selectid=2\r\nvalsbefor=0=--корень--', '1'),
(69, 68, 5, 'name', 'txt', 'formtit-name', 'txt', '0', '', 1, '1', 'style=width:100%', '1'),
(68, 0, 5, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(70, 68, 5, 'type', 'txt', 'formtit-type', 'select', '0', 'formtit-type-tooltip', 2, '1', 'valsbefor=sim=Простой|dif=Сложный', '1'),
(71, 68, 5, 'sim_values', 'txt', 'formtit-simvalues', 'txtarea', '0', '', 3, '1', 'w=100%\r\nh=70px', '1'),
(72, 84, 5, 'dif_fields', 'txt', 'formtit-dif_fields', 'txt', '0', '', 1, '1', 'style=width:100%', '1'),
(73, 84, 5, 'dif_tblname', 'txt', 'formtit-dif_tblname', 'txt', '0', '', 2, '1', 'style=width:100%', '1'),
(74, 84, 5, 'dif_cond', 'txt', 'formtit-dif_cond', 'txt', '0', '', 3, '1', 'style=width:100%', '1'),
(75, 84, 5, 'dif_sort', 'txt', 'formtit-dif_sort', 'txt', '0', '', 4, '1', 'style=width:100%', '1'),
(76, 84, 5, 'dif_startpid', 'int', 'formtit-dif_startpid', 'txt', '0', '', 5, '1', 'style=width:100%', '1'),
(77, 84, 5, 'dif_startspace', 'int', 'formtit-dif_startspace', 'txt', '0', '', 6, '1', 'style=width:100%', '1'),
(78, 84, 5, 'dif_spacer', 'txt', 'formtit-dif_spacer', 'txt', '0', '', 7, '1', 'style=width:100%', '1'),
(79, 84, 5, 'dif_defval', 'txt', 'formtit-dif_defval', 'txt', '0', '', 9, '1', 'style=width:100%', '1'),
(80, 84, 5, 'dif_keyfield', 'txt', 'formtit-dif_keyfield', 'txt', '0', '', 8, '1', 'style=width:100%', '1'),
(81, 84, 5, 'dif_valfield', 'txt', 'formtit-dif_valfield', 'txt', '0', '', 10, '1', 'style=width:100%', '1'),
(82, 84, 5, 'dif_optcond', 'txt', 'formtit-dif_optcond', 'txt', '0', '', 11, '1', 'style=width:100%', '1'),
(84, 0, 5, '', 'txt', 'admc_bm-difsel', 'txt', '0', '', 2, '1', '', '1'),
(88, 84, 5, 'dif_valsbefor', 'txt', 'formtit-dif_valsbefor', 'txtarea', '0', '', 12, '1', 'w=100%\r\nh=70', '1'),
(89, 84, 5, 'dif_valsafter', 'txt', 'formtit-dif_valsafter', 'txtarea', '0', '', 13, '1', 'w=100%\r\nh=70', '1'),
(112, 0, 11, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(133, 128, 12, 'record_id', 'int', NULL, 'hid', '0', '', 6, '1', '', '1'),
(134, 128, 12, 'sort', 'int', NULL, 'hid', '0', '', 7, '1', '', '1'),
(115, 0, 12, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(116, 115, 12, 'pid', 'txt', 'form-pid', 'select', '0', 'tooltip-pid', 1, '1', 'selectid=3', '1'),
(117, 115, 12, 'title', 'txt', 'form-title', 'txt', '0', 'tooltip-title', 2, '1', 'style=width:100%', '1'),
(118, 115, 12, 'url', 'txt', 'form-url', 'lid', '0', 'tooltip-url', 3, '1', 'linkfname=title', '1'),
(119, 115, 12, 'public', 'txtint', 'form-public', 'checkbox', '0', 'tooltip-public', 4, '1', '', '1'),
(120, 115, 12, 'include_in_pathway', 'txtint', 'form-include_in_pathway', 'checkbox', '0', 'tooltip-include_in_pathway', 5, '1', '', '1'),
(121, 115, 12, 'pathway', 'txt', 'form-pathway', 'txt', '0', 'tooltip-pathway', 6, '1', 'style=width:100%', '1'),
(123, 0, 12, '', 'txt', 'admc_bm-metas', 'txt', '0', '', 2, '1', '', '1'),
(124, 123, 12, 'meta_title', 'txt', 'form-meta_title', 'txt', '0', 'tooltip-meta_title', 1, '1', 'style=width:100%', '1'),
(125, 123, 12, 'meta_keywords', 'txt', 'form-meta_keywords', 'txtarea', '0', 'tooltip-meta_keywords', 2, '1', 'w=100%\r\nh=100', '1'),
(126, 123, 12, 'meta_description', 'txt', 'form-meta_description', 'txtarea', '0', 'tooltip-meta_description', 3, '1', 'w=100%\r\nh=100', '1'),
(127, 128, 12, 'getsubpages_deep', 'int', 'form-getsubpages_deep', 'txt', '0', 'tooltip-getsubpages_deep', 5, '1', '', '1'),
(128, 0, 12, '', 'txt', 'admc_bm-comp', 'txt', '0', '', 3, '1', '', '1'),
(129, 128, 12, 'component', 'txt', 'form-component', 'select', '0', 'tooltip-component', 1, '1', 'selectid=10', '1'),
(130, 128, 12, 'template', 'txt', 'form-template', 'select', '0', 'tooltip-template', 2, '1', 'selectid=4', '1'),
(131, 128, 12, 'tplfile', 'txt', 'form-tplfile', 'select', '0', 'tooltip-tplfile', 3, '1', 'selectid=11', '1'),
(132, 128, 12, 'getsubpages', 'txtint', 'form-getsubpages', 'checkbox', '0', 'tooltip-getsubpages', 4, '1', '', '1'),
(135, 0, 14, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(136, 135, 14, 'name', 'txt', 'form-name', 'txt', '0', '', 1, '1', 'style=width:100%', '1'),
(137, 135, 14, 'code', 'txt', 'form-code', 'txt', '0', '', 2, '1', 'style=width:100%', '1'),
(138, 135, 14, 'sort', 'int', 'form-sort', 'txt', '0', '', 3, '1', '', '1'),
(139, 135, 14, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 4, '1', '', '1'),
(140, 0, 15, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(141, 140, 15, 'mid', 'int', 'form-mid', 'select', '0', '', 1, '1', 'selectid=6\r\ndeffromfilter_code=mid\r\ndeffromfilter_way=menulist/items', '1'),
(142, 140, 15, 'name', 'txt', 'form-name', 'txt', '0', '', 2, '1', 'style=width:100%', '1'),
(143, 140, 15, 'link', 'txt', 'form-link', 'link-select', '0', '', 3, '1', 'selectid=7', '1'),
(144, 140, 15, 'sort', 'int', 'form-sort', 'txt', '0', '', 4, '1', '', '1'),
(145, 140, 15, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 5, '1', '', '1'),
(146, 140, 15, 'target', 'txt', 'form-target', 'select', '0', '', 6, '1', 'valsbefor=_self=В том же окне|_blank=В новом окне', '1'),
(147, 140, 15, 'pid', 'int', 'form-pid', 'select', '0', '', 1, '1', 'selectid=3', '1'),
(148, 0, 16, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(149, 148, 16, 'name', 'txt', 'form-name', 'txt', '0', '', 1, '1', 'style=width:100%', '1'),
(150, 148, 16, 'sort', 'int', 'form-sort', 'txt', '0', '', 2, '0', '', '1'),
(151, 148, 16, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 3, '0', '', '1'),
(152, 0, 17, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(160, 0, 4, '', 'txt', 'admc_bm-settings', 'txt', '0', '', 1, '1', '', '1'),
(159, 160, 4, 'add_button', 'txt', 'form-add_button', 'select', '0', '', 1, '1', 'selectid=12', '1'),
(158, 157, 18, 'img', 'txt', 'form-img', 'file', '0', '', 1, '1', 'type=img\r\nfpath1=/images/photos/small/\r\nfpath2=/images/photos/big/\r\next=png,jpeg,jpg,gif\r\nreplace=1\r\nresize=1\r\nw1=200\r\nh1=0\r\nw2=800\r\nh2=0\r\nnewext=\r\nislink=1\r\ncond_resize1=1\r\nsave2name=_rand_', '1'),
(157, 0, 18, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(161, 160, 4, 'tpl_file', 'txt', 'form-tpl_file', 'txt', '0', '', 2, '1', '', '1'),
(162, 160, 4, 'get_subpages', 'int', 'form-get_subpages', 'txt', '0', '', 3, '1', '', '1'),
(163, 160, 4, 'parent_parts', 'txt', 'form-parent_parts', 'txt', '0', '', 4, '1', '', '1'),
(164, 0, 19, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(165, 160, 4, 'use_component', 'txt', 'form-use_component', 'txt', '0', '', 5, '1', '', '1'),
(166, 160, 4, 'limit', 'int', 'form-limit', 'txt', '0', '', 6, '1', '', '1'),
(167, 160, 4, 'enabled', 'txtint', 'form-enabled', 'checkbox', '0', '', 7, '1', '', '1'),
(168, 0, 20, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(169, 157, 18, 'title', 'txt', 'form-title', 'txt', '0', '', 2, '1', 'style=width:100%', '1'),
(170, 157, 18, 'description', 'txt', 'form-description', 'txtarea', '0', '', 3, '1', 'w=100%\r\nh=100', '1'),
(171, 157, 18, 'pid', 'int', NULL, 'hid', '0', '', 4, '1', '', '1'),
(172, 157, 18, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 5, '1', '', '1'),
(173, 168, 20, 'img', 'txt', 'form-img', 'file', '0', '', 1, '1', 'type=img\r\nfpath1=/images/photos/small/\r\nfpath2=/images/photos/big/\r\next=png,jpeg,jpg,gif\r\nreplace=1\r\nresize=1\r\nw1=200\r\nh1=0\r\nw2=800\r\nh2=0\r\nnewext=\r\nislink=1\r\ncond_resize1=1\r\nsave2name=_rand_', '1'),
(174, 168, 20, 'title', 'txt', 'form-title', 'txt', '0', '', 2, '1', 'style=width:100%', '1'),
(175, 168, 20, 'description', 'txt', 'form-description', 'txtarea', '0', '', 3, '1', 'w=100%\r\nh=100', '1'),
(176, 168, 20, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 4, '1', '', '1'),
(177, 140, 15, 'page_id', 'txt', NULL, 'hid', '0', '', 7, '1', '', '1'),
(210, 160, 4, 'content_tpl_by', 'int', 'form-content_tpl_by', 'txt', '0', '', 8, '1', '', '1'),
(179, 21, 3, 'countries', 'txt', 'form-countries', 'txtarea', '0', 'tooltip-countries', 7, '0', 'w=100%\r\nh=100', '1'),
(180, 21, 3, 'cities', 'txt', 'form-cities', 'txtarea', '0', 'tooltip-cities', 8, '0', 'w=100%\r\nh=100', '1'),
(181, 0, 22, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(182, 0, 23, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(183, 182, 23, 'name', 'txt', 'form-name', 'txt', '0', '', 1, '1', 'style=width:100%', '1'),
(184, 182, 23, 'text', 'txt', 'form-text', 'txtarea', '0', '', 2, '1', 'w=100%\r\nh=50', '1'),
(185, 182, 23, 'img', 'txt', 'form-img', 'file', '0', '', 3, '1', 'type=img\r\nfpath1=/images/catalog/cat/\r\nsave2name=_rand_\r\next=png,jpeg,jpg,gif\r\nreplace=1\r\nresize=1\r\nw1=220\r\nh1=160\r\nnewext=\r\nislink=1\r\ncond_resize1=1', '1'),
(186, 0, 24, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(187, 0, 25, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(188, 187, 25, 'name', 'txt', 'form-name', 'txt', '1', 'tooltip-name', 1, '1', 'style=width:100%', '1'),
(189, 187, 25, 'pid', 'txt', NULL, 'hid', '0', '', 0, '1', '', '1'),
(192, 187, 25, 'matirial', 'txt', 'form-matirial', 'txt', '0', '', 4, '1', 'style=width:100%', '1'),
(190, 187, 25, 'title', 'txt', 'form-title', 'txt', '1', 'tooltip-title', 2, '1', 'style=width:100%', '1'),
(191, 187, 25, 'artikul', 'txt', 'form-artikul', 'txt', '0', '', 3, '1', 'style=width:100%', '1'),
(193, 187, 25, 'substrate', 'txt', 'form-substrate', 'txt', '0', '', 5, '1', 'style=width:100%', '1'),
(194, 187, 25, 'size', 'txt', 'form-size', 'txt', '0', 'tooltip-size', 6, '1', 'style=width:100%', '1'),
(195, 187, 25, 'delivery', 'txt', 'form-delivery', 'txt', '0', '', 7, '1', 'style=width:100%', '1'),
(196, 187, 25, 'cur_price', 'txt', 'form-cur_price', 'txt', '0', '', 8, '1', 'style=width:100%', '1'),
(197, 187, 25, 'old_price', 'txt', 'form-old_price', 'txt', '0', 'tooltip-old_price', 9, '1', 'style=width:100%', '1'),
(198, 187, 25, 'description', 'txt', 'form-description', 'txtarea', '0', '', 10, '1', 'w=100%\r\nh=100', '1'),
(199, 187, 25, 'public', 'txtint', 'form-public', 'checkbox', '0', '', 11, '1', '', '1'),
(200, 187, 25, 'color', 'txt', 'form-color', 'txt', '0', '', 12, '1', 'style=width:100%', '1'),
(201, 0, 25, '', 'txt', 'admc_bm-fotos', 'txt', '0', '', 2, '1', '', '1'),
(202, 201, 25, 'imgdirname', 'txt', NULL, 'hid', '0', '', 2, '1', '', '0'),
(204, 201, 25, 'osnfotodirname', 'txt', NULL, 'hid', '0', '', 3, '1', '', '1'),
(205, 201, 25, 'osnfotoname', 'txt', NULL, 'hid', '0', '', 4, '1', '', '1'),
(206, 187, 25, 'new', 'txtint', 'form-new', 'checkbox', '0', '', 13, '1', '', '1'),
(207, 0, 26, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(208, 0, 27, '', 'txt', 'admc_bm-content', 'txt', '0', '', 1, '1', '', '1'),
(209, 21, 3, 'use_pathway', 'txtint', 'form-use_pathway', 'checkbox', '0', '', 9, '0', '', '1'),
(211, 0, 3, '', 'txt', 'admc_bm-metadatas', 'txt', '0', '', 2, '1', '', '1'),
(212, 211, 3, 'title', 'txt', 'config-f-title', 'txt', '0', 'config-t-title', 1, '1', 'style=width:100%', '1'),
(213, 211, 3, 'keywords', 'txt', 'config-f-keywords', 'txtarea', '0', 'config-t-keywords', 2, '1', 'w=100%\r\nh=50', '1'),
(214, 211, 3, 'description', 'txt', 'config-f-description', 'txtarea', '0', 'config-t-description', 3, '1', 'w=100%\r\nh=50', '1'),
(215, 211, 3, 'title_autofill', 'txt', 'config-f-title_autofill', 'txt', '0', 'config-t-title_autofill', 4, '1', 'style=width:100%', '1'),
(216, 160, 4, 'nodelete', 'txtint', 'component-manage-f-nodelete', 'checkbox', '0', '', 9, '1', '', '1');
CREATE TABLE IF NOT EXISTS `#h_components_listtable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `com_id` int(11) NOT NULL DEFAULT '0',
  `db_fname` varchar(255) NOT NULL DEFAULT '',
  `mui_title` varchar(20) NOT NULL DEFAULT '',
  `type` enum('plaintext','index','switch','datetime','field','del','edit','linked','lid','img','fromselect') DEFAULT 'plaintext',
  `params` text NOT NULL,
  `edit` enum('0','1') NOT NULL DEFAULT '0',
  `del` enum('0','1') NOT NULL DEFAULT '0',
  `nosort` enum('0','1') NOT NULL DEFAULT '0',
  `sort` smallint(6) NOT NULL DEFAULT '0',
  `public` enum('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=131 ;
INSERT INTO `#h_components_listtable` (`id`, `com_id`, `db_fname`, `mui_title`, `type`, `params`, `edit`, `del`, `nosort`, `sort`, `public`) VALUES
(51, 12, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(50, 12, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(49, 12, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(8, 4, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(9, 4, 'man_title', 'man_title', 'plaintext', 'style=text-align:left;\r\nspacer=|-&nbsp;', '0', '0', '0', 0, '1'),
(10, 4, 'adm_title', 'adm_title', 'plaintext', '', '0', '0', '0', 0, '1'),
(11, 4, 'title', 'title', 'plaintext', '', '1', '0', '0', 0, '1'),
(12, 4, 'url', 'url', 'lid', '', '1', '0', '0', 0, '0'),
(13, 4, 'sort', 'sort', 'field', '', '1', '0', '0', 0, '0'),
(14, 4, 'cache_page', 'cache_page', 'switch', '', '1', '0', '0', 0, '0'),
(15, 4, 'cache_page_ttl', 'cache_page_ttl', 'field', '', '1', '0', '0', 0, '0'),
(16, 4, '', 'edit', 'edit', '', '1', '0', '1', 0, '1'),
(17, 4, '', 'delete', 'del', '', '0', '1', '1', 0, '1'),
(22, 5, 'name', 'name', 'plaintext', '', '0', '0', '0', 2, '1'),
(21, 5, '', 'index', 'index', '', '0', '0', '1', 1, '1'),
(23, 5, '', 'edit', 'edit', '', '1', '0', '1', 4, '1'),
(24, 5, '', 'delete', 'del', '', '0', '1', '1', 5, '1'),
(25, 5, 'type', 'type', 'plaintext', '', '0', '0', '0', 3, '1'),
(52, 12, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(53, 12, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(54, 14, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(55, 14, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(56, 14, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(57, 14, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(58, 14, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(59, 14, 'name', 'name', 'plaintext', 'linkto=/{adm_path}/menulist/items/?mid={thisid}\r\nshownumber=mid|__menupunkti', '0', '0', '0', 1, '1'),
(60, 14, 'code', 'code', 'plaintext', '', '0', '0', '0', 2, '1'),
(61, 15, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(62, 15, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(63, 15, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(64, 15, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(65, 15, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(66, 15, 'name', 'name', 'plaintext', 'style=text-align:left;\r\nspacer=&nbsp;&nbsp;&nbsp;', '0', '0', '0', 1, '1'),
(67, 15, 'mid', 'mid', 'fromselect', 'selectid=6', '0', '0', '0', 2, '1'),
(68, 16, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(69, 16, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(70, 16, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(71, 16, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(72, 16, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(73, 16, 'name', 'name', 'plaintext', 'spacer=|-\r\nshownumber=cid|__fotogalery_con\r\nlinkto=/{adm_path}/fotogalery/content/?cid={thisid}', '0', '0', '0', 1, '1'),
(85, 18, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(83, 18, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(82, 18, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(81, 18, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(84, 18, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(86, 19, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(87, 19, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(88, 19, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(89, 19, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(90, 19, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(91, 20, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(92, 20, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(93, 20, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(94, 20, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(95, 20, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(96, 20, 'title', 'title', 'plaintext', '', '0', '0', '0', 1, '1'),
(97, 20, 'img', 'img', 'img', 'fpath1=photos/small\r\nfpath2=photos/big\r\nw=70', '0', '0', '0', 2, '1'),
(98, 22, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(99, 22, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(100, 22, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(101, 22, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(102, 22, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(103, 23, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(104, 23, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(105, 23, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(106, 23, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(107, 23, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(108, 24, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(109, 24, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(110, 24, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(111, 24, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(112, 24, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(113, 25, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(114, 25, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(115, 25, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(116, 25, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(117, 25, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(118, 25, 'name', 'name', 'plaintext', '', '0', '0', '0', 2, '1'),
(119, 25, 'title', 'title', 'plaintext', '', '0', '0', '0', 1, '1'),
(120, 25, 'new', 'new', 'switch', '', '1', '0', '0', 3, '1'),
(121, 26, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(122, 26, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(123, 26, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(124, 26, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(125, 26, '', 'delete', 'del', '', '0', '1', '1', 99, '1'),
(126, 27, '', 'index', 'index', '', '0', '0', '1', 0, '1'),
(127, 27, 'sort', 'sort', 'field', '', '1', '0', '0', 96, '1'),
(128, 27, 'public', 'public', 'switch', '', '1', '0', '0', 97, '1'),
(129, 27, '', 'edit', 'edit', '', '1', '0', '1', 98, '1'),
(130, 27, '', 'delete', 'del', '', '0', '1', '1', 99, '1');
CREATE TABLE IF NOT EXISTS `#h_components_selects` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '',
  `type` enum('sim','dif') NOT NULL DEFAULT 'sim',
  `sim_values` text NOT NULL,
  `dif_fields` varchar(255) NOT NULL DEFAULT '',
  `dif_tblname` varchar(255) NOT NULL DEFAULT '',
  `dif_cond` varchar(255) NOT NULL DEFAULT '',
  `dif_sort` varchar(255) NOT NULL DEFAULT '',
  `dif_startpid` int(11) NOT NULL DEFAULT '0',
  `dif_startspace` smallint(6) NOT NULL DEFAULT '0',
  `dif_spacer` varchar(50) NOT NULL DEFAULT '',
  `dif_defval` varchar(255) NOT NULL DEFAULT '',
  `dif_keyfield` varchar(255) NOT NULL DEFAULT '',
  `dif_valfield` varchar(255) NOT NULL DEFAULT '',
  `dif_optcond` varchar(255) NOT NULL DEFAULT '',
  `dif_valsbefor` text NOT NULL,
  `dif_valsafter` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=13 ;
INSERT INTO `#h_components_selects` (`id`, `name`, `type`, `sim_values`, `dif_fields`, `dif_tblname`, `dif_cond`, `dif_sort`, `dif_startpid`, `dif_startspace`, `dif_spacer`, `dif_defval`, `dif_keyfield`, `dif_valfield`, `dif_optcond`, `dif_valsbefor`, `dif_valsafter`) VALUES
(1, 'adm_admlang', 'sim', 'ru=Русский\r\nen=English', '', '', '', '', 0, 0, '', '', '', '', '', '', ''),
(2, 'Список компонентов', 'dif', '', 'id, pid, man_title', 'h_components', '`id`!={thisid}', '`sort`, `man_title` ASC', 0, 0, '|', '', 'id', 'man_title', '', '', ''),
(3, 'Дерево сайта', 'dif', '', '*', '__sitemap', '`id`!={thisid} && `type`=''page''', '`sort` ASC', 0, 0, '   ', '', 'id', 'title', '', '0=-корень сайта-', ''),
(4, 'Список шаблонов данных', 'dif', '', 'id, pid, title, man_title', 'h_components', '`title` NOT LIKE ''''', '`sort`, `man_title` ASC', 0, 0, '--', '', 'title', 'man_title', '', '0=нет', ''),
(5, 'Список параметров', 'dif', '', 'id, par, par_name', 's_params', '1', '', 0, 0, '', '', 'par', 'par_name', '', '', ''),
(6, 'Список меню', 'dif', '', 'id, pid, name', '__menulist', '1', '`sort`,`name` ASC', 0, 0, '--', '', 'id', 'name', '', '0=--- выберите ---', ''),
(7, 'Дерево сайта для списка меню', 'dif', '', '*', '__sitemap', '`type`=''page''', '`sort` ASC', 0, 0, '--', '', 'url', 'title', '', '', ''),
(10, 'Список компонентов', 'sim', 'default=по-умолчанию', '', '', '', '', 0, 0, '', '', '', '', '', '', ''),
(11, 'Список шаблонов', 'sim', 'text.php=Текстовая страница\r\ncontact.php=Контакты с формой\r\nfotogalery_cat.php=Все категории фотогалереи\r\nfotogalery_onecat.php=Выбранная категория фотогалереи', '', '', '', '', 0, 0, '', '', '', '', '', '', ''),
(12, 'Тип компонента', 'sim', '0=нет\r\nrazdel=Раздел\r\ncontent=Контент', '', '', '', '', 0, 0, '', '', '', '', '', '', '');
CREATE TABLE IF NOT EXISTS `#h_mailfromsite` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fromemail` varchar(200) NOT NULL DEFAULT '',
  `tema` varchar(255) NOT NULL DEFAULT '',
  `head` text NOT NULL,
  `text` text NOT NULL,
  `date` int(11) NOT NULL DEFAULT '0',
  `toemail` varchar(200) NOT NULL DEFAULT '',
  `readed` enum('0','1') NOT NULL DEFAULT '0',
  `par` varchar(150) NOT NULL DEFAULT '',
  `sended` enum('0','1') NOT NULL DEFAULT '0',
  `touid` int(11) NOT NULL DEFAULT '0' COMMENT 'id юзера, кому отправили письмо',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='mails from site';
CREATE TABLE IF NOT EXISTS `#h_moduls` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL DEFAULT '',
  `man_title` varchar(200) NOT NULL DEFAULT '',
  `version` varchar(50) NOT NULL DEFAULT '',
  `cache_page` enum('0','1') NOT NULL DEFAULT '0',
  `cache_page_ttl` smallint(6) NOT NULL DEFAULT '0',
  `editable` enum('0','1') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='moduls of this site';
INSERT INTO `#h_moduls` (`id`, `title`, `man_title`, `version`, `cache_page`, `cache_page_ttl`, `editable`) VALUES
(1, 'htmlhead', 'Заголовок <head>', '1.0.', '0', 0, '0'),
(2, 'pathway', 'Хлебные крошки', '1.0.', '0', 0, '0'),
(3, 'text', 'текстовый блок', '1.0.', '0', 0, '0'),
(4, 'navigation', 'навигация', '1.0.', '0', 0, '0');
CREATE TABLE IF NOT EXISTS `#h_statistic` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` bigint(20) NOT NULL DEFAULT '0',
  `page` tinytext NOT NULL,
  `ref` tinytext NOT NULL,
  `date` int(11) NOT NULL DEFAULT '0',
  `reg_id` int(11) NOT NULL DEFAULT '0',
  `time2gen` int(11) NOT NULL DEFAULT '0',
  `page_status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='statistic visitors';
CREATE TABLE IF NOT EXISTS `#h_statistic_admin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `aid` int(11) NOT NULL DEFAULT '0',
  `ip` varchar(50) NOT NULL DEFAULT '',
  `date` int(11) NOT NULL DEFAULT '0',
  `page` tinytext NOT NULL,
  `time2gen` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='statistic admins';
CREATE TABLE IF NOT EXISTS `#h_statistic_users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ip` varchar(50) NOT NULL DEFAULT '',
  `session` varchar(50) NOT NULL DEFAULT '',
  `useragent` varchar(255) NOT NULL DEFAULT '',
  `browser` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='statistic users';
CREATE TABLE IF NOT EXISTS `#h_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(200) NOT NULL DEFAULT '',
  `pas` varchar(50) NOT NULL DEFAULT '',
  `rpascode` varchar(100) NOT NULL DEFAULT '',
  `scode` varchar(100) NOT NULL DEFAULT '',
  `email` varchar(200) NOT NULL DEFAULT '',
  `name` varchar(200) NOT NULL DEFAULT '',
  `otchestvo` varchar(200) NOT NULL DEFAULT '',
  `family` varchar(200) NOT NULL DEFAULT '',
  `date_reg` int(11) NOT NULL DEFAULT '0',
  `date_lastvizit` int(11) NOT NULL DEFAULT '0',
  `group` smallint(6) NOT NULL DEFAULT '0',
  `activ` enum('0','1') NOT NULL DEFAULT '0',
  `site_tpl` varchar(100) NOT NULL DEFAULT '',
  `adm_tpl` varchar(100) NOT NULL DEFAULT '',
  `phone` varchar(100) NOT NULL DEFAULT '',
  `icq` varchar(20) NOT NULL DEFAULT '',
  `skype` varchar(100) NOT NULL DEFAULT '',
  `region` varchar(100) NOT NULL DEFAULT '',
  `city` varchar(100) NOT NULL DEFAULT '',
  `street` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='users of this site';
CREATE TABLE IF NOT EXISTS `#h_users_groups` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `isadmin` enum('0','1') NOT NULL DEFAULT '0',
  `adm_index_page` varchar(50) NOT NULL DEFAULT 'index',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='groups of users';
INSERT INTO `#h_users_groups` (`id`, `name`, `isadmin`, `adm_index_page`) VALUES
(1, 'Боги', '1', 'index_bog'),
(2, 'Менеджеры', '1', 'index'),
(3, 'простой пользователь', '0', '');
CREATE TABLE IF NOT EXISTS `#h_users_rights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `gid` smallint(6) NOT NULL DEFAULT '0',
  `way` varchar(255) NOT NULL DEFAULT '',
  `view` enum('0','1') NOT NULL DEFAULT '0',
  `edit` enum('0','1') NOT NULL DEFAULT '0',
  `delete` enum('0','1') NOT NULL DEFAULT '0',
  `add` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 PACK_KEYS=0 AUTO_INCREMENT=26 ;
INSERT INTO `#h_users_rights` (`id`, `pid`, `gid`, `way`, `view`, `edit`, `delete`, `add`) VALUES
(1, 0, 1, 'index_bog', '1', '1', '1', '1'),
(2, 0, 2, 'index', '1', '1', '1', '1'),
(3, 0, 2, 'text', '1', '1', '1', '1'),
(4, 0, 1, 'users_groups', '1', '1', '1', '1'),
(5, 0, 1, 'users_groups/users', '1', '1', '1', '1'),
(6, 0, 2, 'textmodul', '1', '1', '1', '1'),
(9, 0, 2, 'config', '1', '1', '1', '1'),
(10, 0, 1, 'component-manage', '1', '1', '1', '1'),
(13, 10, 1, 'adm_title', '1', '1', '0', '1'),
(14, 10, 1, 'version', '1', '0', '0', '1'),
(15, 0, 1, 'select-manage', '1', '1', '1', '1'),
(18, 0, 2, 'pageconfig', '1', '1', '1', '1'),
(19, 0, 2, 'menulist', '1', '1', '1', '1'),
(20, 0, 2, 'menulist/items', '1', '1', '1', '1'),
(24, 0, 2, 'foto', '0', '0', '0', '0'),
(25, 0, 2, 'fotogalery', '0', '0', '0', '0'),
(26, 0, 2, 'filemanager', '1', '0', '0', '0'),
(27, 0, 2, 'userconfig', '1', '1', '0', '0'),
(28, 0, 2, 'sort_items', '1', '0', '0', '0'),
(29, 0, 1, 'ajax-fieditmanage', '1', '1', '1', '1'),
(30, 0, 1, 'ajax-filistmanage', '1', '1', '1', '1'),
(31, 0, 1, 'mui_control', '1', '1', '1', '1'),
(32, 0, 2, 'photos_set', '1', '1', '1', '1');
ALTER TABLE  `#h_components` ADD  `content_tpl_by` INT NOT NULL;

CREATE TABLE IF NOT EXISTS `#h_adm_widgets` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `url` varchar(200) NOT NULL,
  `img` varchar(50) NOT NULL,
  `sort` smallint(6) NOT NULL,
  `public` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1251 AUTO_INCREMENT=6 ;
INSERT INTO `#h_adm_widgets` (`id`, `url`, `img`, `sort`, `public`) VALUES
(1, '/{adm_path}/textmodul/', 'textmodul.png', 1, '1'),
(2, '/{adm_path}/config/', 'config.png', 2, '1'),
(3, '/{adm_path}/menulist/', 'menuedit.png', 3, '1'),
(4, '/{adm_path}/users_groups/users/?gid=3', 'users.png', 4, '0'),
(5, '/{adm_path}/filemanager/', 'file_manager.png', 5, '1');

CREATE TABLE IF NOT EXISTS `#h_mui` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group` varchar(50) NOT NULL,
  `param` varchar(10) NOT NULL,
  `mui_code` varchar(50) NOT NULL,
  `mui_text` varchar(255) NOT NULL,
  `adm` enum('0','1') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `#h_mui` (`id`, `group`, `param`, `mui_code`, `mui_text`, `adm`) VALUES
(NULL, 'error404', 'ru', 'error404-pagenotfound', 'Cтраница не найдена', '0'),
(NULL, 'error404', 'ru', 'error404-describe', 'Запрашиваемая страница не найдена. Возможно вы ввели не корректный адрес.', '0'),
(NULL, 'error404', 'ru', 'error404-go2home', 'Перейти на главную страницу', '0'),
(NULL, 'common', 'ru', 'admc_add', 'добавить', '1'),
(NULL, 'common', 'ru', 'admc_record_add', 'Запись добавлена', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc_record_edited', 'Запись отредактирована', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc_button_save', 'сохранить', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc_button_applay', 'применить', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc_button_cancel', 'отмена', '1'),
(NULL, 'common', 'ru', 'adm_access2part_deny', '<strong>Ошибка:</strong> раздел не существует, либо доступ запрещён', '1'),
(NULL, 'common', 'ru', 'adm_itemedit', 'редактировать', '1'),
(NULL, 'common', 'ru', 'adm_itemadd', 'добавить', '1'),
(NULL, '', 'ru', 'adm_buttonadd', 'добавить', '1'),
(NULL, '', 'ru', 'adm_buttonsave', 'сохранить', '1'),
(NULL, '', 'ru', 'adm_buttonapplay', 'применить', '1'),
(NULL, '', 'ru', 'adm_buttoncancel', 'отмена', '1'),
(NULL, 'common', 'ru', 'adm_switchno', 'нет', '1'),
(NULL, 'common', 'ru', 'adm_switchyes', 'да', '1'),
(NULL, 'common', 'ru', 'adm_itemdelquestion', 'Удалить?', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'adm_noitems', 'нет записей', '1'),
(NULL, '', 'ru', 'adm_itemdelcanttooltip', 'невозможно удалить', '1'),
(NULL, 'common', 'ru', 'adm_itemdeltooltip', 'удалить запись', '1'),
(NULL, '', 'ru', 'adm_itemeditcanttooltip', 'невозможно отредактировать', '1'),
(NULL, 'common', 'ru', 'adm_itemedittooltip', 'отредактировать запись', '1'),
(NULL, 'common', 'ru', 'adm_userchecklist_showuser', 'смотреть/редактировать пользователя в новом окне', '1'),
(NULL, 'common', 'ru', 'adm_userchecklist_login', 'логин', '1'),
(NULL, 'common', 'ru', 'adm_userchecklist_usernotset', 'пользователь не задан', '1'),
(NULL, 'common', 'ru', 'adm_userchecklist_setuser', 'установить пользователя', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_usernotset', 'пользователь не задан', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_nomails', 'писем нет', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_from', 'От', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_to', 'Кому', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_thema', 'Тема', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_date', 'Дата', '1'),
(NULL, '', 'ru', 'adm_mailfromsite_senderror', 'Ошибка при отправке', '1'),
(NULL, '', 'ru', 'adm_showsaveico_save', 'сохранить', '1'),
(NULL, '', 'ru', 'adm_savex_savemes', 'изменения внесены', '1'),
(NULL, '', 'ru', 'adm_switchrow_savemes', 'запись отредактирована', '1'),
(NULL, 'common', 'ru', 'adm_delrow_del', 'запись удалена', '1'),
(NULL, '', 'ru', 'adm_closeeditform_unfilled', 'не заполнено обязательное поле', '1'),
(NULL, '', 'ru', 'fs_directory_nochoosedir', 'папка не выбрана', '1'),
(NULL, '', 'ru', 'fs_directory_choosefolder', 'выбрать папку / загрузить файлы (фото)', '1'),
(NULL, '', 'ru', 'fs_directory_setthisdir', 'выбрать папку', '1'),
(NULL, 'common', 'ru', 'adm_showfile_delimg', 'удалить картинку', '1'),
(NULL, '', 'ru', 'adm_showfile_delfile', 'удалить файл', '1'),
(NULL, 'common', 'ru', 'adm_showfile_notuploaded', 'файл не загружен', '1'),
(NULL, 'common', 'ru', 'adm_showfile_choosefile', 'Выберите файл, макс. размер', '1'),
(NULL, '', 'ru', 'adm_showfile_upnotallowed', 'Загрузка файлов запрещена в настройках PHP (php.ini). Обратитесь к вашему администратору сервера.', '1'),
(NULL, 'common', 'ru', 'adm_showfile_upnodir', 'Директория для загрузки файла не существует', '1'),
(NULL, 'common', 'ru', 'adm_lidedit', 'редактировать', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'adm_autotranslit', 'автоматическая транслитерация url', '1'),
(NULL, 'common', 'ru', 'adm_lidwar', 'Внимание! адрес страницы изменился. Это может привести к неработающим ссылкам на сайте.', '1'),
(NULL, 'common', 'ru', 'adm_lidwarretdef', 'вернуть изначальный адрес', '1'),
(NULL, '', 'ru', 'adm_addprelid', 'Добавить вначало ссылки адрес родительской страницы', '1'),
(NULL, 'common', 'ru', 'adm_uploadfile_ok', 'файл загружен', '1'),
(NULL, '', 'ru', 'adm_uploadfile_err', 'ошибка при загрузке файла', '1'),
(NULL, '', 'ru', 'adm_uploadfile_unsupfiletype', 'недопустимый тип файла', '1'),
(NULL, '', 'ru', 'adm_uploadfile_filesaveerror', 'ошибка при сохранении файла', '1'),
(NULL, '', 'ru', 'adm_uploadfile_savedascopy', 'Файл с указанным именем существует, новый файл загружен под именем', '1'),
(NULL, '', 'ru', 'adm_uploadfile_savesuc', 'загрузка файла прошла успешно', '1'),
(NULL, '', 'ru', 'adm_deletefile_notfound', 'файл не найден', '1'),
(NULL, '', 'ru', 'adm_changepas_war1', 'Пароль не изменён. Необходимо ввести новый пароль и его подтверждение.', '1'),
(NULL, '', 'ru', 'adm_changepas_war2', 'Пароль не изменён. Новый пароль и подтверждение пароля не совпадают.', '1'),
(NULL, '', 'ru', 'adm_changepas_war3', 'Пароль не изменён. Указан неверный текущий пароль.', '1'),
(NULL, '', 'ru', 'adm_changepas_ok1', 'Пароль изменён.', '1'),
(NULL, '', 'ru', 'adm_changepas_war4', 'Пароль не задан. Необходимо ввести пароль и его подтверждение.', '1'),
(NULL, '', 'ru', 'adm_changepas_war5', 'Пароль не задан. Пароль и подтверждение пароля не совпадают.', '1'),
(NULL, '', 'ru', 'adm_changepas_ok2', 'Пароль задан.', '1'),
(NULL, 'common', 'ru', 'admc_filter-strok', 'Строк на страницу', '1'),
(NULL, '', 'ru', 'record_added', 'запись добалена', '1'),
(NULL, '', 'ru', 'record_edited', 'запись отредактрована', '1'),
(NULL, '', 'ru', 'record_unsaved', 'Информация не сохранена', '1'),
(NULL, 'common', 'ru', 'password_cur', 'Текущий пароль', '1'),
(NULL, 'common', 'ru', 'password_new1', 'Новый пароль1', '1'),
(NULL, 'common', 'ru', 'password_new2', 'Новый пароль2', '1'),
(NULL, 'common', 'ru', 'email', 'Контактный email', '1'),
(NULL, 'common', 'ru', 'button_save', 'сохранить', '1'),
(NULL, '', 'ru', 'admc_title', 'Содержимое', '1'),
(NULL, 'common', 'ru', 'sort_by_parent_page', 'Сортировка записей к записи', '1'),
(NULL, 'common', 'ru', 'go_up', 'Перейти выше', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'save', 'Сохранить сортировку', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'cancel', 'Отмена (вернуться, не сохранять)', '1'),
(NULL, 'common', 'ru', 'no_published', 'Запись не опубликована на сайте', '1'),
(NULL, 'common', 'ru', 'sort_sub_pages', 'Сортировать вложенные записи', '1'),
(NULL, '', 'ru', 'select-manage:admc_title', 'Управление селектами', '1'),
(NULL, 'common', 'ru', 'admc_error_duplicateurl', 'Ошибка. Страница с таким url уже существует (Шаг 2)', '1'),
(NULL, 'common', 'ru', 'admc_error_nourl', 'Ошибка. Не задан url страницы (Шаг 2)', '1'),
(NULL, '', 'ru', 'admc_error_notitle', 'Ошибка. Не задан зоголовок страницы (Шаг 2)', '1'),
(NULL, '', 'ru', 'admc_error_noparent', 'Ошибка. Не выбран раздел для добавления (Шаг 1)', '1'),
(NULL, 'common', 'ru', 'admc_record_edit', 'Запись отредактирована', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc1_button_save', 'сохранить', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc1_button_applay', 'применить', '1'),
(NULL, 'Админка : кнопки управления', 'ru', 'admc1_button_cancel', 'отмена', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'step', 'Шаг', '1'),
(NULL, '', 'ru', 'from', 'из', '1'),
(NULL, '', 'ru', 'click_next', 'По завершению выбора нажмите "далее"', '1'),
(NULL, '', 'ru', 'click_save', 'По завершению выбора нажмите "сохранить"', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_root', '-- Корневой раздел --', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'form-title', 'Название', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'form-url', 'Адрес страницы', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'title_pathway', '<b>Хлебные крошки</b> (<a href="http://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D1%86%D0%B5%D0%BF%D0%BE%D1%87%D0%BA%D0%B0" target="_blank">узнать, что такое хлебные крошки</a>)', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'form-include_in_pathway', 'Использовать в х.к.', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'form-pathway', 'Вид в х.к.', '1'),
(NULL, '', 'ru', 'tooltip-pathway', 'Задав текст в этом поле Вы измените отображение заголовка этой страницы при выводе на сайте в хлебных крошках', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'selectmenu', 'Выберите меню', '1'),
(NULL, 'Адм : меню', 'ru', 'selectparentpunkt', 'Родительский пункт', '1'),
(NULL, 'Адм : меню', 'ru', 'textoflink', 'Текст ссылки', '1'),
(NULL, 'Адм : меню', 'ru', 'linksort', 'Сортировка', '1'),
(NULL, 'Адм : меню', 'ru', 'openlinkin', 'Открывать', '1'),
(NULL, 'Адм : меню', 'ru', 'openlinkin_self', 'в том же окне', '1'),
(NULL, 'Адм : меню', 'ru', 'openlinkin_blank', 'в новом окне', '1'),
(NULL, '', 'ru', 'admc_button_back', 'назад', '1'),
(NULL, '', 'ru', 'admc_button_next', 'далее', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_here', 'будет размещено тут', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'textoflinkgettitle', 'Поставить заголовок страницы', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:admc_title', 'Управление языками', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:chooselan', 'Выберите язык', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:nogroup', '- нет группы -', '1'),
(NULL, '', 'ru', 'mui_control:selectpart', 'Часть сайта', '1'),
(NULL, '', 'ru', 'mui_control:isadm0', 'сам сайт', '1'),
(NULL, '', 'ru', 'mui_control:isadm1', 'админка', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:selectgroup', 'Выберите группу', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:allgroups', '- все группы -', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:group_self', 'Новая группа', '1'),
(NULL, 'АдминкаБог : управление языками', 'ru', 'mui_control:group', 'граппа', '1'),
(NULL, 'Адм : меню', 'ru', 'menulist:admc_title', 'Меню', '1'),
(NULL, 'Адм : меню', 'ru', 'menulist_items:admc_title', 'Меню / Пункты меню', '1'),
(NULL, '', 'ru', 'savebutton', 'Сохранить изменения', '1'),
(NULL, '', 'ru', 'go_sort_title', 'Упорядочить фотографии', '1'),
(NULL, '', 'ru', 'proceedsort', 'Перед сортировкой сохраните введённые данные, иначе они будут потеряны. Продолжить?', '1'),
(NULL, '', 'ru', 'go_sort_diti', 'Упорядочить список категорий', '1'),
(NULL, '', 'ru', 'nopictures', 'нет ниодной фотографии', '1'),
(NULL, '', 'ru', 'tpl_site', 'Сайт', '1'),
(NULL, 'Админка : Диалоговые окна', 'ru', 'sitemap_sort_dialog_title', 'Сортировать страницы сайта', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'sitemap_sort_btn_title', 'Сортировать страницы сайта', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_sitemaploading', 'карта сайта загружается, пожалуйста ждите...', '1'),
(NULL, 'common', 'ru', 'userconf', 'Настройки пользователя', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'userconflink', 'сменить пароль', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'exitfromadm', 'Выйти из панели администрирования', '1'),
(NULL, 'Админка : FileManager', 'ru', 'filemanager_title', 'вы тут', '1'),
(NULL, '', 'ru', 'thisisnotdir', 'Запрошенной папки не существует', '1'),
(NULL, '', 'ru', 'uploadedfilescol', 'Загружено файлов', '1'),
(NULL, '', 'ru', 'createdir_err', 'Папка НЕ создана', '1'),
(NULL, 'Админка : FileManager', 'ru', 'createdir_ok', 'Папка создана', '1'),
(NULL, 'Админка : FileManager', 'ru', 'loadwait', 'Подождите, загрузка содержимого папки', '1'),
(NULL, '', 'ru', 'cantuploadfile', 'Нет прав на создание папок и загрузку файлов в эту папку.', '1'),
(NULL, 'Админка : FileManager', 'ru', 'uplfilesbtn', 'загрузить файлы', '1'),
(NULL, '', 'ru', 'uploadfile', 'Загрузить файл(ы) в эту папку', '1'),
(NULL, '', 'ru', 'upmorefiles', 'добавить полей для загрузки файлов', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_click_text', 'Клик, чтобы выбрать файлы', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_uploading_text', 'Идёт загрузка', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_complete_text', 'Загрузка завершена', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_pending_text', 'Ожидание загрузки', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_max_text', 'Достигнут лимит файлов', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_valid_text', 'Недопустимый тип файла', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_size_failure_text', 'Размер файла превышен', '1'),
(NULL, 'Админка : FileManager', 'ru', 'flaupl_progress_text', 'Идёт загрузка', '1'),
(NULL, 'Админка : FileManager', 'ru', 'max_file_size', 'Максимальный размер одного файла', '1'),
(NULL, 'Админка : FileManager', 'ru', 'createfolder', 'Создать тут папку', '1'),
(NULL, 'Админка : FileManager', 'ru', 'createfoldername', 'Имя создаваемой папки', '1'),
(NULL, 'Админка : FileManager', 'ru', 'createfolderdescr', 'Описание папки', '1'),
(NULL, 'Админка : FileManager', 'ru', 'delselected', 'Удалить выделенные файлы/папки', '1'),
(NULL, 'Админка : FileManager', 'ru', 'needdirname', 'Задайте имя создоваемой папки', '1'),
(NULL, 'Админка : FileManager', 'ru', 'deletequestion', 'Файлы и папки будут удалены безвозвратно. Удалить?', '1'),
(NULL, 'Админка : FileManager', 'ru', 'contextmenu_delete', 'Удалить', '1'),
(NULL, 'Админка : FileManager', 'ru', 'contextmenu_properties', 'Свойства', '1'),
(NULL, '', 'ru', 'admc_bm-editor', 'Текстовый редактор', '1'),
(NULL, 'Список компонентов', 'ru', 'component-manage:admc_title', 'Список компонентов', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_newtable_created', 'Новая таблица компонента создана', '1'),
(NULL, '', 'ru', 'admc_newtable_notcreated_ex', 'Новая таблица компонента не создана. Таблица с таким именем уже существует', '1'),
(NULL, '', 'ru', 'admc_oldtable_del', 'Старая таблица компонента удалена', '1'),
(NULL, '', 'ru', 'admc_newtable_renamed', 'Старая таблица компонента переименована в новое имя', '1'),
(NULL, '', 'ru', 'admc_newtable_norenamed_ex', 'Старая таблица компонента не переименована в новое имя. Таблица с таким именем уже существует', '1'),
(NULL, '', 'ru', 'admc_js_error1', 'Ошибка! Не удалось найти ячейку с конфигом', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_js_txt1', 'Заданные параметры', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable_type1', 'Только если не существует с таким именем', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable_type2', 'Заменить существующую с таким именем', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable_type3', 'Переименовать старую в новое имя', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable', 'C таблицей компонента (параметр: <i>tbl</i>):', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable-0', 'Ничего не делать', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable-1', 'Создать, условие создания:', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_conf_createtable-2', 'Удалить', '1'),
(NULL, '', 'ru', 'admc_create_config_tbl-2-confirm', 'Удалить текущую таблицу компонента? Данные будут безвозвратно утеряны.', '1'),
(NULL, '', 'ru', 'admc_conf_createtable_type2_confirm', 'Удалить существующую таблицу с таким именем (если она есть)? Все данные будут безвозвратно удалены.', '1'),
(NULL, '', 'ru', 'admc_conf_createtable_type12_confirm1', 'Существующая таблица компонента будет удалена. Продолжить?', '1'),
(NULL, 'Админка : общие настройки', 'ru', 'adm_pagetitle', 'управление сайтом', '1'),
(NULL, '', 'ru', 'adm_exitq', 'Выйти из панели управления?', '1'),
(NULL, '', 'ru', 'adm_exit', 'выйти', '1'),
(NULL, 'постраничная навигация', 'ru', 'adm_page', 'Страница', '1'),
(NULL, 'постраничная навигация', 'ru', 'adm_pagefrom', 'из', '1'),
(NULL, '', 'ru', 'adm_tomainpage', 'на главную', '1'),
(NULL, '', 'ru', 'adm_previouspage', 'предыдущая', '1'),
(NULL, 'постраничная навигация', 'ru', 'adm_topage', 'перейти на', '1'),
(NULL, 'постраничная навигация', 'ru', 'adm_page1', 'страницу', '1'),
(NULL, 'постраничная навигация', 'ru', 'adm_nextpage', 'следующая', '1'),
(NULL, '', 'ru', 'adm_tolastpage', 'на последнюю', '1'),
(NULL, 'Админка : про CMS', 'ru', 'cms_core_version', 'Версия ядра', '1'),
(NULL, 'Админка : про CMS', 'ru', 'cms_adm_version', 'Версия админки', '1'),
(NULL, 'Админка : Диалоговые окна', 'ru', 'dialogloadstat', 'Загрузка...', '1'),
(NULL, 'Страница входа', 'ru', 'adm_avtorization', 'Авторизация', '1'),
(NULL, 'Страница входа', 'ru', 'adm_login', 'Логин', '1'),
(NULL, 'Страница входа', 'ru', 'adm_enter', 'Вход', '1'),
(NULL, 'Страница входа', 'ru', 'adm_password', 'Пароль', '1'),
(NULL, 'Страница входа', 'ru', 'adm_cms', 'Система управления Вашим веб-сайтом', '1'),
(NULL, '', 'ru', 'adm_ajwaitdursaving', 'Подождите, идёт добавление...', '1'),
(NULL, 'common', 'ru', 'adm_ajsaved', 'Сохранено', '1'),
(NULL, '', 'ru', 'rxstat_no', 'нет', '1'),
(NULL, '', 'ru', 'rxstat_createmuifile', 'Создать этот файл', '1'),
(NULL, '', 'ru', 'rxstat_params_list_def', 'По-умолчанию', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_openpageinnw', 'открыть страницу в новом окне', '1'),
(NULL, 'common', 'ru', 'content_inside', 'Внутри содержимого:', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_pagetype', 'тип', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_editpage', 'редактировать страницу', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'editbutton', 'редактировать', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_delpage', 'удалить страницу', '1'),
(NULL, '', 'ru', 'tpl_movepagedown', 'переместить страницу ниже', '1'),
(NULL, '', 'ru', 'tpl_movepageup', 'переместить страницу выше', '1'),
(NULL, 'common', 'ru', 'root', 'Корень', '1'),
(NULL, 'common', 'ru', 'ls_sel_self', 'Свой вариант', '1'),
(NULL, 'common', 'ru', 'ls_sel_fromlist', 'Из списка', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_paramedited', 'Параметры отредактированы', '1'),
(NULL, '', 'ru', 'admc_parameditederr', 'Ошибка при редактировании параметров', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_fieldadded', 'Поле добавлено', '1'),
(NULL, '', 'ru', 'admc_fieldaddederr', 'Ошибка при добавлении поля', '1'),
(NULL, 'common', 'ru', 'admc_fielddel', 'Поле удалено', '1'),
(NULL, '', 'ru', 'admc_fielddelerr', 'Ошибка при удалении поля', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_field', 'Поле БД', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_mui', 'mui код', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_type', 'Тип поля формы', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_params', 'Параметры', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_edit', 'Редактирование', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_del', 'Удаление', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_nosort', 'Cортировать', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_sort', 'Порядок', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_public', 'Показывать', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_act', 'Действие', '1'),
(NULL, 'common', 'ru', 'admc_tdmanage_delconf', 'Удалить поле?', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_addfield', 'Добавить поле', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_lb_type_dir', 'Тип', '1'),
(NULL, '', 'ru', 'prop_val_type_dir', 'Папка с файлами', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_lb_type_file', 'Файл', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_lb_type_name', 'Имя', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_val_type_file_user', 'в файловом менеджере', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_val_type_file_ondisk', 'на диске (для формирования ссылки на файл)', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_val_type_file_link', 'Ссылка на файл для вставки в редактор', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_lb_size', 'Размер', '1'),
(NULL, '', 'ru', 'prop_lb_', 'no_mui:prop_lb_', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_save', 'Сохранить и закрыть окно', '1'),
(NULL, '', 'ru', 'file_namedisk_exists', 'Файл или папка с таким именем на диске уже существует', '1'),
(NULL, '', 'ru', 'file_namefmdir_exists', 'Папка с таким именем в файловом менеджере уже существует', '1'),
(NULL, '', 'ru', 'file_namefm_exists', 'Файл с таким именем в файловом менеджере уже существует', '1'),
(NULL, '', 'ru', 'error', 'Ошибка', '1'),
(NULL, 'Админка : FileManager', 'ru', 'goback', 'назад', '1'),
(NULL, 'Админка : FileManager', 'ru', 'emptydir', 'Папка пуста', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_js_txt2', 'Вставить параметры', '1'),
(NULL, '', 'ru', 'admc_edbmadd', 'Новая закладка добавлена', '1'),
(NULL, '', 'ru', 'admc_edbmadderr', 'Ошибка при добавлении новой закладки', '1'),
(NULL, 'Список компонентов', 'ru', 'self_var', 'Свой вариант', '1'),
(NULL, 'common', 'ru', 'act_del', 'Удалить', '1'),
(NULL, 'Список компонентов', 'ru', 'bmsorttitle', 'порядок', '1'),
(NULL, 'Список компонентов', 'ru', 'addfieldtitle', '+добавить поле', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_typedb', 'Тип поля БД', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_tooltipmui', 'mui подсказки', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_req', 'Обязательное', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tbhat_useinsql', 'в sql', '1'),
(NULL, 'common', 'ru', 'act_move1', 'Перенести в', '1'),
(NULL, 'common', 'ru', 'act_move', 'Перенести в другую закладку', '1'),
(NULL, 'Список компонентов', 'ru', 'addbmtitle', 'Добавить закладку', '1'),
(NULL, '', 'ru', 'admc_fieldadderror', 'Ошибка при добавлении поля', '1'),
(NULL, '', 'ru', 'admc_fieldediterror', 'Ошибка при редактировании поля', '1'),
(NULL, '', 'ru', 'admc_fieldedited', 'Поле отредактировано', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_table', 'Таблица БД', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_field', 'Поле', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_type', 'Тип (Длина/Значение)', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_default', 'По умолчанию', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_edit', 'Редактировать', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_del', 'Удалить', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_tdmanage_addtitle', 'Добавить поле', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_addafter', 'добавить после', '1'),
(NULL, 'common', 'ru', 'adm_ajlogin', 'Логин', '1'),
(NULL, 'common', 'ru', 'adm_ajfio', 'Фио', '1'),
(NULL, 'common', 'ru', 'adm_ajset', 'Выбрать', '1'),
(NULL, 'common', 'ru', 'adm_ajsetusernotify', 'Пользователь выбран', '1'),
(NULL, 'common', 'ru', 'adm_ajcloseuserlist', 'отмена', '1'),
(NULL, 'Кнопки добавления страниц', 'ru', 'tpl_addpart', 'Добавить', '1'),
(NULL, 'Кнопки добавления страниц', 'ru', 'add_button_21', 'Раздел', '1'),
(NULL, 'Кнопки добавления страниц', 'ru', 'add_button_2', 'Текстовую страницу', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_tbl', 'Таблица контента компонента', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_trashfname', 'имя поля таблицы БД по которому сохраняем в корзину', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_colonpage_var', 'варианты для фильтра \"записей на страницу\"', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_colonpage_def', 'значение по умолчанию для фильтра \"записей на страницу\"', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_editbut-save', 'показывать кнопку \"сохранить\" (1 - да', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_editbut-apply', 'показывать кнопку \"применить\" (1 - да', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_editbut-cancel', 'показывать кнопку \"отмена\" (1 - да', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_defid', 'при добавлении/редактировании записи', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_pidfield', 'если данные в БД представляют из себя дерево', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_sc_colonpage', 'Число записей', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_sort_fieldtitle', 'Имя поля БД', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_sort_blocksstyle', 'CSS Стиль блока. Если написать {images}', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_sort_sqlextra', 'Дополнительные условия sql запроса', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_sort_notree', 'Если \"1\", то записи не представлены в виде дерева	', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_w', 'ширина картинки (превьюшки)', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_confparams_tooltip_h', 'высота картинки (превьюшки)', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_linkto', 'сделает текст в данном поле ссылкой на указанный урл. {adm_path} - адрес админки', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_style', 'стиль', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_spacer', 'спейсер', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_shownumber', 'покажет в этом поле после самого текста в скобках число записей из таблицы {__} где поле cid = id из текущей БД', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_type', 'тип (img/file)', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_fpath1', 'путь до папки картинки', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_save2name', 'сохранять с этим именем (_rand_ - лучайно генерировать имя). Без расширения!', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_ext', 'принимать файлы с этим расширением', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_replace', 'заменять файл', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_resize', 'изменять разрешение картинки (1 - да', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_w1', 'ширина новой картинки', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_h1', 'высота новой картинки', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_newext', 'сохранять с этим расширением (если не менять расширение загружаемого файла', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_islink', 'в админке не показывать привью а показывать просто ссылку (1 - да', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_extra', 'дополнительный HTML к полю', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_cond_resize1', 'условия пережимания картинки. -1 - пережимать если истинный размер картинки меньше', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_selectid', 'id селекта', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_valsbefor', 'Подставить значения в селект в начало. Задаётся в виде key=val|key=val', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_valsafter', 'Подставить значения в селект в конец. Задаётся в виде key=val|key=val', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_deffromfilter_way', 'Если не задано значение', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_deffromfilter_code', 'Если не задано значение', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_format', 'формат даты для функции date()', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_default', 'Если это поле пустое', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_fpath2', 'путь до папки картинки', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_accgids', 'id групп юзеров для показа через запятую', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_acctype', 'тип показа: 0 - показывать все группы; 1 - показывать только пользователей из групп указаннх в $accgid; 2 - показывать пользователей из групп НЕ указаннх в $accgid;', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_showfields', 'имена дополнительных полей БД', '1'),
(NULL, 'Админка : FileManager', 'ru', 'file_size_mb', 'Мб', '1'),
(NULL, 'Админка : карта сайта', 'ru', 'tpl_pagepub1', 'опубликована на сайте', '1'),
(NULL, '', 'ru', 'tpl_pagepub0', 'НЕ опубликована на сайте', '1'),
(NULL, 'Виджеты', 'ru', 'widget_name_1', 'текстовые модули', '1'),
(NULL, 'Виджеты', 'ru', 'widget_name_2', 'настройки сайта', '1'),
(NULL, 'Виджеты', 'ru', 'widget_name_3', 'настройки меню', '1'),
(NULL, 'Виджеты', 'ru', 'widget_name_4', 'Пользователи', '1'),
(NULL, 'Виджеты', 'ru', 'widget_name_5', 'файлы', '1'),
(NULL, 'common', 'ru', 'tpl_editpart', 'Редактировать', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_contetn_step1_desc', 'Выберите родительский раздел', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_contetn_step2_desc', 'Задайте заголовок страницы и адрес', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_contetn_step3_desc', 'Задайте Мета-Данные для этой страницы. Они необходимы для лучшей индексации вашего сайта поисковыми системами', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_contetn_step4_desc', 'Если нужна ссылка на создаваемую страницу из меню, задайте её тут', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'add_contetn_step5_desc', 'Тут Вы можете отредактировать содержимое страницы', '1'),
(NULL, 'Админка : добавление страницы', 'ru', 'admclist_index', '#', '1'),
(NULL, 'Адм : меню', 'ru', 'admclist_name', 'Название', '1'),
(NULL, 'Адм : меню', 'ru', 'admclist_code', 'Код', '1'),
(NULL, 'common', 'ru', 'admclist_sort', 'Сортировка', '1'),
(NULL, 'common', 'ru', 'admclist_public', 'Опубликовано', '1'),
(NULL, 'common', 'ru', 'admclist_edit', 'редактировать', '1'),
(NULL, 'common', 'ru', 'admclist_delete', 'удалить', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_man_title', 'Название', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_adm_title', 'Код', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_title', 'title', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_url', 'url', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_cache_page', 'Кэш страниц', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_cache_page_ttl', 'Время жизни кэша страниц', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_version', 'Версия', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_config', 'Конфиг компонента', '1'),
(NULL, 'Список компонентов', 'ru', 'admclist_pid', 'Родитель', '1'),
(NULL, 'Адм : меню', 'ru', 'admclist_mid', 'Меню', '1'),
(NULL, '', 'ru', 'admclist_type', 'Тип', '1'),
(NULL, 'Админка : FileManager', 'ru', 'prop_lb_', 'no_mui:prop_lb_', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'admc_comedit-home_url', 'Главная страница', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'form-cemail', 'E-mail администратора', '1'),
(NULL, 'common', 'ru', 'admc_bm-content', 'содержание', '1'),
(NULL, 'Адм : меню', 'ru', 'form-name', 'Имя', '1'),
(NULL, 'Адм : меню', 'ru', 'form-code', 'Код', '1'),
(NULL, 'Адм : меню', 'ru', 'form-sort', 'Сортировка', '1'),
(NULL, 'Адм : меню', 'ru', 'form-public', 'Опубликовать', '1'),
(NULL, 'Адм : меню', 'ru', 'form-mid', 'Меню', '1'),
(NULL, 'Адм : меню', 'ru', 'form-pid', 'Родитель', '1'),
(NULL, 'Адм : меню', 'ru', 'form-link', 'Ссылка', '1'),
(NULL, 'Адм : меню', 'ru', 'form-target', 'Открывать в', '1'),
(NULL, 'Админка : FileManager', 'ru', 'file_size_b', 'байт', '1'),
(NULL, 'Редактирование : текстовая страница', 'ru', 'admc_comedit-text', 'Текст', '1'),
(NULL, 'Страница входа', 'ru', 'login_error', 'неверный логин или пароль', '1'),
(NULL, 'Страница входа', 'ru', 'logout_mes', 'Вы вышли', '1'),
(NULL, 'Список компонентов', 'ru', 'form-add_button', 'Тип', '1'),
(NULL, 'Список компонентов', 'ru', 'form-tpl_file', 'Файл шаблона', '1'),
(NULL, 'Список компонентов', 'ru', 'form-get_subpages', 'Брать подстраниц', '1'),
(NULL, 'Список компонентов', 'ru', 'form-parent_parts', 'Относится к разделам', '1'),
(NULL, 'Список компонентов', 'ru', 'form-use_component', 'Компонент', '1'),
(NULL, 'Список компонентов', 'ru', 'form-limit', 'Макс. число копий', '1'),
(NULL, 'Список компонентов', 'ru', 'form-enabled', 'Можно устанавливать', '1'),
(NULL, 'Список компонентов', 'ru', 'form-content_tpl_by', 'Контент по шаблону', '1'),
(NULL, 'Список компонентов', 'ru', 'admc_bm-settings', 'Настройки', '1'),
(NULL, 'Список компонентов', 'ru', 'component-manage-f-nodelete', 'Нельзя удалять', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_linkfname', 'Имя поля, относительно которого делаем транслит для url', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_fm_dir', 'Директория с файлами (без слешей вначале и вконце)', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_dir_field_here', 'Имя поля БД в котором хранится адрес папки с фотографиями тут', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_dir_field_there', 'Имя поля БД в котором хранится адрес папки с фотографиями в таблице с фотографиями', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_img_field_there', 'Имя поля БД в котором хранится имя фотографии в таблице с фотографиями', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_com_id', 'id компонента, обрабатывающий редактирование фото', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_noactid', 'список idшников, которые нельзя удалять/редактировать через запятую', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_dt', 'mui сообщения подтверждения удаления', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_linkfield', 'это поле из таблицы (выше) должно равняться текущему значению колонки, чтобы взять значение поля (ниже)', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_showfield', 'показывать значение этого поля', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_defval', 'показывать это, если из базы не удалось взять строку', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-name', 'Имя', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-type', 'Тип', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-type-tooltip', 'Тип селекта: простой или сложный', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-simvalues', 'Значения для простого селекта', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_fields', 'Поля из БД', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_tblname', 'Из таблицы БД', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_cond', 'Условие выборки', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_sort', 'Условие сортировки', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_startpid', 'Начальный pid', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_startspace', 'Начальный отступ', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_spacer', 'Разделитель', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_keyfield', 'Поле - ключ', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_defval', 'По умолчанию', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_valfield', 'Поле - значение', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_optcond', 'optcond', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_valsbefor', 'Значения в начале', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'formtit-dif_valsafter', 'Значения в конце', '1'),
(NULL, 'АдминкаБог : управление селектами', 'ru', 'admc_bm-difsel', 'Сложный select', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_userfname', 'имя поля в котором хранится id пользователя', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_skin', 'скин', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_wys_type', 'тип редактора', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_class', 'имя CSS класса', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_default_checked', 'по-умолчанию отмечен', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_sub_page_tbl', 'Таблица компонента, на котором работают подстраницы к данной странице', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_sub_page_of', 'Сортировать список подстраниц по этому полю БД из таблицы компонента подстраниц', '1'),
(NULL, 'Бог : параметры компонента', 'ru', 'admc_confparams_tooltip_sub_page_oc', 'Условие сортировки подстраниц при наборе', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'admc_bm-metadatas', 'Метаданные', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-f-title', 'title', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-f-keywords', 'keywords', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-f-description', 'description', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-f-title_autofill', 'дополнение title', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-t-title', 'используется, если не задан конкретный title страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-t-keywords', 'используется, если не задан конкретный keywords страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-t-description', 'используется, если не задан конкретный description страницы', '1'),
(NULL, 'Редактирование : конфиг сайта', 'ru', 'config-t-title_autofill', 'подставляется к title каждой страницы справа', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'ph_set_noimg', 'Нет ниодного изображения', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'ph_set_delimg', 'Удалить изображение', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'ph_set_delimgconfirm', 'Изображение будет удалено безвозвратно. Продолжить?', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'photogalery_addph_tooltip', 'Кликните "Клик, чтобы выбрать файлы" ниже и выберите файлы для загрузки. После завершения загрузки нажмите "Готово"', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'photogalery_addph_fileexts', 'Допустимые типы файлов', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'photogalery_addph_done', 'Готово', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'photogalery_addph_button', 'Загрузить изображения', '1'),
(NULL, 'admin : photogalery_add_photo', 'ru', 'photogalery_addph_noiderror', 'Сохраните страницу, чтобы иметь возможность загружать фотографии. Нажмите кнопку "Сохранить" или "Применить"', '1');